---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: 'SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter. È necessario creare credenziali per l"installazione dei plug-in SnapCenter e credenziali aggiuntive per l"esecuzione delle operazioni di protezione dei dati su database o file system Windows.' 
---
= Impostare le credenziali per il pacchetto di plug-in SnapCenter per Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter. È necessario creare credenziali per l'installazione dei plug-in SnapCenter e credenziali aggiuntive per l'esecuzione delle operazioni di protezione dei dati su database o file system Windows.

*Cosa ti serve*

* Prima di installare i plug-in, è necessario impostare le credenziali di Windows.
* È necessario impostare le credenziali con privilegi di amministratore, inclusi i diritti di amministratore sull'host remoto.
* Autenticazione SQL su host Windows
+
È necessario impostare le credenziali SQL dopo l'installazione dei plug-in.

+
Se si implementa il plug-in SnapCenter per Microsoft SQL Server, è necessario impostare le credenziali SQL dopo l'installazione dei plug-in. Impostare una credenziale per un utente con autorizzazioni sysadmin di SQL Server.

+
Il metodo di autenticazione SQL esegue l'autenticazione con un'istanza di SQL Server. Ciò significa che un'istanza di SQL Server deve essere rilevata in SnapCenter. Pertanto, prima di aggiungere una credenziale SQL, è necessario aggiungere un host, installare pacchetti plug-in e aggiornare le risorse. È necessaria l'autenticazione di SQL Server per eseguire operazioni come la pianificazione o il rilevamento delle risorse.



*Fasi*

. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *credenziale*.
. Fare clic su *nuovo*.
. Nella pagina credenziale, specificare le informazioni necessarie per la configurazione delle credenziali:
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Nome della credenziale
 a| 
Immettere un nome per la credenziale.



 a| 
Nome utente/Password
 a| 
Immettere il nome utente e la password da utilizzare per l'autenticazione.

** Amministratore di dominio
+
Specificare l'amministratore di dominio sul sistema su cui si sta installando il plug-in SnapCenter. I formati validi per il campo Nome utente sono:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Amministratore locale (solo per gruppi di lavoro)
+
Per i sistemi appartenenti a un gruppo di lavoro, specificare l'amministratore locale incorporato nel sistema in cui si installa il plug-in SnapCenter. È possibile specificare un account utente locale che appartiene al gruppo di amministratori locali se l'account utente dispone di privilegi elevati o se la funzione di controllo dell'accesso utente è disattivata sul sistema host. Il formato valido per il campo Nome utente è: `UserName`

+
Non utilizzare virgolette doppie (") o backtick (`) nelle password. Non utilizzare il valore inferiore a (<) e il punto esclamativo (!) simboli insieme nelle password. Ad esempio, meno di<!10, meno di 10<!, backtick`12.





 a| 
Modalità di autenticazione
 a| 
Selezionare la modalità di autenticazione che si desidera utilizzare. Se si seleziona la modalità di autenticazione SQL, è necessario specificare anche l'istanza di SQL Server e l'host in cui si trova l'istanza SQL.

|===
. Fare clic su *OK*.


Al termine dell'impostazione delle credenziali, è possibile assegnare la manutenzione delle credenziali a un utente o a un gruppo di utenti nella pagina User and Access (utenti e accesso).
