---
permalink: protect-scsql/task_define_a_backup_strategy_for_sql_server_resources.html 
sidebar: sidebar 
keywords:  
summary: 'La definizione di una strategia di backup prima di creare i processi di backup consente di garantire la presenza dei backup necessari per ripristinare o clonare correttamente i database. Il tuo Service Level Agreement (SLA), Recovery Time Objective (RTO) e Recovery Point Objective (RPO) determinano in gran parte la tua strategia di backup.' 
---
= Definire una strategia di backup per le risorse di SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La definizione di una strategia di backup prima di creare i processi di backup consente di garantire la presenza dei backup necessari per ripristinare o clonare correttamente i database. Il Service Level Agreement (SLA), l'RTO (Recovery Time Objective) e l'RPO (Recovery Point Objective) determinano in gran parte la strategia di backup.

Uno SLA definisce il livello di servizio previsto e risolve molti problemi relativi al servizio, tra cui la disponibilità e le performance del servizio. L'RTO è il momento in cui un processo di business deve essere ripristinato dopo un'interruzione del servizio. Un RPO definisce la strategia per l'età dei file che devono essere ripristinati dallo storage di backup per consentire il ripristino delle normali operazioni dopo un errore. SLA, RTO e RPO contribuiscono alla strategia di backup.
