---
permalink: protect-scsql/task_disaster_recovery_scsql.html 
sidebar: sidebar 
keywords:  
summary: Quando il plug-in SnapCenter per SQL Server non è disponibile, attenersi alla procedura descritta di seguito per ripristinare il plug-in. 
---
= Disaster recovery del plug-in SnapCenter per SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando il plug-in SnapCenter per SQL Server non è attivo, attenersi alla seguente procedura per passare a un host SQL diverso e ripristinare i dati.

.Di cosa hai bisogno
* L'host secondario deve avere lo stesso sistema operativo, l'applicazione e il nome host dell'host primario.
* Trasferire il plug-in SnapCenter per SQL Server a un host alternativo utilizzando la pagina *Aggiungi host* o *Modifica host*. Vedere link:https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_hosts.html["Gestire gli host"] per ulteriori informazioni.


.Fasi
. Selezionare l'host dalla pagina *hosts* per modificare e installare il plug-in SnapCenter per SQL Server.
. (Facoltativo) sostituire il plug-in SnapCenter per i file di configurazione di SQL Server dal backup di disaster recovery (DR) al nuovo computer.
. Importare pianificazioni Windows e SQL dalla cartella del plug-in SnapCenter per SQL Server dal backup DR.


.Per ulteriori informazioni
Vedere link:https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["API di disaster recovery"^] video.
