---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-clone.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, clone 
summary: SnapCenter consente di utilizzare le variabili di ambiente predefinite quando si eseguono prespt e postscript durante la clonazione di un database. 
---
= Variabili di ambiente predefinite per il clone specifico prespt e postscript
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter consente di utilizzare le variabili di ambiente predefinite quando si eseguono prespt e postscript durante la clonazione di un database.

*Variabili di ambiente predefinite supportate per la clonazione di un database*

* *SC_ORIGINAL_SID* specifica il SID del database di origine.
+
Questo parametro verrà popolato per i volumi dell'applicazione.

+
Esempio: NFSB32

* *SC_ORIGINAL_HOST* specifica il nome dell'host di origine.
+
Questo parametro verrà popolato per i volumi dell'applicazione.

+
Esempio: asmrac1.gdl.englab.netapp.com

* *SC_ORACLE_HOME* specifica il percorso della home directory Oracle del database di destinazione.
+
Esempio: /Ora01/app/oracle/product/18.1.0/db_1

* *SC_BACKUP_NAME*" specifica il nome del backup.
+
Questo parametro verrà popolato per i volumi dell'applicazione.

+
Esempi:

+
** Se il database non è in esecuzione in modalità ARCHIVELOG: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** Se il database è in esecuzione in modalità ARCHIVELOG: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG:RG2_scspr2417819002_07-20-2021_12.16.48.9267_1,RG2_scspr2417819002_07-21-2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1


* *SC_AV_NAME* specifica i nomi dei volumi dell'applicazione.
+
Esempio: AV1|AV2

* *SC_ORIGINAL_OS_USER* specifica il proprietario del sistema operativo del database di origine.
+
Esempio: oracle

* *SC_ORIGINAL_OS_GROUP* specifica il gruppo di sistemi operativi del database di origine.
+
Esempio: Oinstall

* *SC_TARGET_SID*" specifica il SID del database clonato.
+
Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito.

+
Questo parametro verrà popolato per i volumi dell'applicazione.

+
Esempio: Clonedb

* *SC_TARGET_HOST* specifica il nome dell'host in cui verrà clonato il database.
+
Questo parametro verrà popolato per i volumi dell'applicazione.

+
Esempio: asmrac1.gdl.englab.netapp.com

* *SC_TARGET_OS_USER* specifica il proprietario del sistema operativo del database clonato.
+
Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito.

+
Esempio: oracle

* *SC_TARGET_OS_GROUP* specifica il gruppo di sistemi operativi del database clonato.
+
Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito.

+
Esempio: Oinstall

* *SC_TARGET_DB_PORT* specifica la porta del database clonato.
+
Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito.

+
Esempio: 1521



Per informazioni sui delimitatori, vedere link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["Delimitatori supportati"^].
