---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Exchange Server 
summary: 'Il plug-in SnapCenter per Microsoft Exchange Server è un componente sul lato host del software NetAppSnapCenter che consente la gestione della protezione dei dati basata sulle applicazioni dei database Exchange. Il plug-in per Exchange automatizza il backup e il ripristino dei database Exchange nell"ambiente SnapCenter.' 
---
= Panoramica del plug-in SnapCenter per il server Microsoft Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per Microsoft Exchange Server è un componente sul lato host del software NetApp SnapCenter che consente la gestione della protezione dei dati basata sulle applicazioni dei database Exchange. Il plug-in per Exchange automatizza il backup e il ripristino dei database Exchange nell'ambiente SnapCenter.

Una volta installato il plug-in per Exchange, è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror dei set di backup su un altro volume e con la tecnologia NetApp SnapVault per eseguire la replica del backup disk-to-disk a scopo di conformità agli standard o di archiviazione.

Se si desidera ripristinare e ripristinare i messaggi e-mail o le caselle postali al posto del database Exchange completo, è possibile utilizzare il software SMBR (Single Mailbox Recovery).
