---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'Il software SMBR (Single Mailbox Recovery) consente di ripristinare e ripristinare i messaggi e-mail o le caselle postali anziché l"intero database Exchange.' 
---
= Ripristino granulare di e-mail e mailbox
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il software SMBR (Single Mailbox Recovery) consente di ripristinare e ripristinare i messaggi e-mail o le caselle postali anziché l'intero database Exchange.

Il ripristino di un database completo solo per recuperare un singolo messaggio di posta consumerà molto tempo e risorse. SMBR consente di recuperare rapidamente i messaggi di posta creando una copia clone di Snapshot e utilizzando le API Microsoft per montare la casella di posta in SMBR. Per informazioni su come utilizzare SMBR, vedere https://["Guida all'amministrazione di SMBR"^].

*Ulteriori informazioni*

* link:../install/concept_snapcenter_licenses.html#single-mailbox-recovery-smbr-licenses["Licenze SMBR"^]
* https://["Libreria di documentazione SMBR"^]
* https://["Come eseguire il ripristino dallo storage secondario in SMBR con SnapCenter"^]
* https://["Ripristino della posta di Microsoft Exchange da SnapVault utilizzando SMBR"^]

