---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: 'SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter. È necessario creare credenziali per l"installazione del pacchetto plug-in e credenziali aggiuntive per l"esecuzione delle operazioni di protezione dei dati sui database.' 
---
= Impostare le credenziali per il plug-in SnapCenter per Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter. È necessario creare credenziali per l'installazione del pacchetto plug-in e credenziali aggiuntive per l'esecuzione delle operazioni di protezione dei dati sui database.

*A proposito di questa attività*

È necessario impostare le credenziali per l'installazione dei plug-in sugli host Windows. Sebbene sia possibile creare credenziali per Windows dopo la distribuzione degli host e l'installazione dei plug-in, la procedura consigliata consiste nel creare credenziali dopo l'aggiunta di SVM, prima di distribuire gli host e installare i plug-in.

Impostare le credenziali con privilegi di amministratore, inclusi i diritti di amministratore sull'host remoto.

Se si impostano le credenziali per singoli gruppi di risorse e il nome utente non dispone di privilegi di amministratore completi, è necessario assegnare almeno il gruppo di risorse e i privilegi di backup al nome utente.

*Fasi*

. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *credenziale*.
. Fare clic su *nuovo*.
+
Viene visualizzata la finestra credenziale.

. Nella pagina Credential, effettuare le seguenti operazioni:
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Nome della credenziale
 a| 
Immettere un nome per la credenziale.



 a| 
Nome utente
 a| 
Inserire il nome utente utilizzato per l'autenticazione.

** Amministratore di dominio o qualsiasi membro del gruppo di amministratori
+
Specificare l'amministratore di dominio o qualsiasi membro del gruppo di amministratori nel sistema in cui si installa il plug-in SnapCenter. I formati validi per il campo Nome utente sono:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Amministratore locale (solo per gruppi di lavoro)
+
Per i sistemi appartenenti a un gruppo di lavoro, specificare l'amministratore locale incorporato nel sistema in cui si installa il plug-in SnapCenter. È possibile specificare un account utente locale che appartiene al gruppo di amministratori locali se l'account utente dispone di privilegi elevati o se la funzione di controllo dell'accesso utente è disattivata sul sistema host. Il formato valido per il campo Nome utente è: `UserName`





 a| 
Password
 a| 
Inserire la password utilizzata per l'autenticazione.



 a| 
Autenticazione
 a| 
Selezionare Windows come modalità di autenticazione.

|===
. Fare clic su *OK*.

