---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Prima di utilizzare i cmdlet PowerShell per eseguire il backup e il ripristino, è necessario creare una connessione SVM (Storage Virtual Machine) e una credenziale.' 
---
= Creare una connessione al sistema di storage e una credenziale utilizzando i cmdlet PowerShell per Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare i cmdlet PowerShell per eseguire il backup e il ripristino, è necessario creare una connessione SVM (Storage Virtual Machine) e una credenziale.

*Cosa ti serve*

* L'ambiente PowerShell dovrebbe essere stato preparato per l'esecuzione dei cmdlet PowerShell.
* Per creare le connessioni storage, è necessario disporre delle autorizzazioni necessarie nel ruolo Infrastructure Admin.
* Assicurarsi che le installazioni dei plug-in non siano in corso.
+
Le installazioni dei plug-in host non devono essere in corso durante l'aggiunta di una connessione al sistema di storage perché la cache host potrebbe non essere aggiornata e lo stato dei database potrebbe essere visualizzato nella GUI di SnapCenter come "`non disponibile per il backup`" o "`non su storage NetApp`".

* I nomi dei sistemi di storage devono essere univoci.
+
SnapCenter non supporta più sistemi storage con lo stesso nome su cluster diversi. Ogni sistema storage supportato da SnapCenter deve avere un nome univoco e un indirizzo IP LIF dei dati univoco.



*Fasi*

. Avviare una sessione di connessione PowerShell utilizzando `Open-SmConnection` cmdlet.
+
Questo esempio apre una sessione PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Creare una nuova connessione al sistema di storage utilizzando `Add-SmStorageConnection` cmdlet.
+
Questo esempio crea una nuova connessione al sistema di storage:

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. Creare un nuovo account Run as utilizzando `Add-Credential` cmdlet.
+
In questo esempio viene creato un nuovo account Run As denominato ExchangeAdmin con credenziali Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].
