---
permalink: protect-sce/task_back_up_exchange_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: backup 
summary: 'Il backup di un database di Exchange Server include la connessione con il server SnapCenter, il rilevamento del database, l"aggiunta di un criterio, la creazione di un gruppo di risorse di backup, il backup e la visualizzazione dello stato del backup.' 
---
= Eseguire il backup delle risorse Exchange utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il backup di un database di Exchange Server include la connessione con il server SnapCenter, il rilevamento del database, l'aggiunta di un criterio, la creazione di un gruppo di risorse di backup, il backup e la visualizzazione dello stato del backup.

*Cosa ti serve*

* È necessario aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.
* È necessario aver aggiunto la connessione al sistema di storage e creato una credenziale.
* È necessario aggiungere host e rilevare risorse.



NOTE: Il plug-in per Exchange non supporta le operazioni di cloni, pertanto il parametro CloneType per il cmdlet Add-SmPolicy non è supportato per il plug-in per Exchange

*Fasi*

. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146/
----
+
Viene visualizzato il prompt di nome utente e password.

. Creare un criterio di backup utilizzando il cmdlet Add-SmPolicy.
+
In questo esempio viene creata una nuova policy di backup con un backup completo e un tipo di backup di log Exchange:

+
[listing]
----
C:\PS> Add-SmPolicy -PolicyName SCE_w2k12_Full_Log_bkp_Policy -PolicyType Backup -PluginPolicytype SCE -SceBackupType FullBackupAndLogBackup -BackupActiveCopies
----
+
In questo esempio viene creata una nuova policy di backup con un backup orario completo e un tipo di backup di log Exchange:

+
[listing]
----
C:\PS> Add-SmPolicy -PolicyName SCE_w2k12_Hourly_Full_Log_bkp_Policy -PolicyType Backup -PluginPolicytype SCE -SceBackupType FullBackupAndLogBackup -BackupActiveCopies -ScheduleType Hourly -RetentionSettings @{'BackupType'='DATA';'ScheduleType'='Hourly';'RetentionCount'='10'}
----
+
Questo esempio crea un nuovo criterio di backup per eseguire il backup solo dei registri di Exchange:

+
[listing]
----
Add-SmPolicy -PolicyName SCE_w2k12_Log_bkp_Policy -PolicyType Backup -PluginPolicytype SCE -SceBackupType LogBackup -BackupActiveCopies
----
. Individuare le risorse host utilizzando il cmdlet Get-SmResources.
+
In questo esempio vengono illustrate le risorse per il plug-in di Microsoft Exchange Server sull'host specificato:

+
[listing]
----
C:\PS> Get-SmResources -HostName vise-f6.sddev.mycompany.com -PluginCode SCE
----
. Aggiungere un nuovo gruppo di risorse a SnapCenter utilizzando il cmdlet Add-SmResourceGroup.
+
In questo esempio viene creato un nuovo gruppo di risorse di backup del database Exchange Server con i criteri e le risorse specificati:

+
[listing]
----
C:\PS> Add-SmResourceGroup -ResourceGroupName SCE_w2k12_bkp_RG -Description 'Backup ResourceGroup with Full and Log backup policy' -PluginCode SCE -Policies SCE_w2k12_Full_bkp_Policy,SCE_w2k12_Full_Log_bkp_Policy,SCE_w2k12_Log_bkp_Policy -Resources @{'Host'='sce-w2k12-exch';'Type'='Exchange Database';'Names'='sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_1,sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2'}
----
+
In questo esempio viene creato un nuovo gruppo di risorse di backup di Exchange Database Availability Group (DAG) con i criteri e le risorse specificati:

+
[listing]
----
Add-SmResourceGroup -ResourceGroupName SCE_w2k12_bkp_RG -Description 'Backup ResourceGroup with Full and Log backup policy' -PluginCode SCE -Policies SCE_w2k12_Full_bkp_Policy,SCE_w2k12_Full_Log_bkp_Policy,SCE_w2k12_Log_bkp_Policy -Resources @{"Host"="DAGSCE0102";"Type"="Database Availability Group";"Names"="DAGSCE0102"}
----
. Avviare un nuovo processo di backup utilizzando il cmdlet New-SmBackup.
+
[listing]
----
C:\PS> New-SmBackup -ResourceGroupName SCE_w2k12_bkp_RG -Policy SCE_w2k12_Full_Log_bkp_Policy
----
+
Questo esempio crea un nuovo backup sullo storage secondario:

+
[listing]
----
New-SMBackup -DatasetName ResourceGroup1 -Policy Secondary_Backup_Policy4
----
. Visualizzare lo stato del processo di backup utilizzando il cmdlet Get-SmBackupReport.
+
Questo esempio visualizza un report di riepilogo di tutti i lavori eseguiti alla data specificata:

+
[listing]
----
C:\PS> Get-SmJobSummaryReport -Date ?1/27/2018?
----
+
Questo esempio visualizza un report di riepilogo del lavoro per un ID lavoro specifico:

+
[listing]
----
C:\PS> Get-SmJobSummaryReport -JobId 168
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, vedere https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].
