---
permalink: protect-scw/reference_sources_and_destinations_of_clones_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: È possibile clonare un backup del file system dallo storage primario o secondario. È inoltre possibile scegliere la destinazione che supporta i requisiti, ovvero la posizione di backup originale o una destinazione diversa sullo stesso host o su un host diverso. La destinazione deve trovarsi sullo stesso volume del backup di origine del clone. 
---
= Origini e destinazioni dei cloni per file system Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un backup del file system dallo storage primario o secondario. È inoltre possibile scegliere la destinazione che supporta i requisiti, ovvero la posizione di backup originale o una destinazione diversa sullo stesso host o su un host diverso. La destinazione deve trovarsi sullo stesso volume del backup di origine del clone.

|===
| Clonare la destinazione | Descrizione 


 a| 
Originale, origine, posizione
 a| 
Per impostazione predefinita, SnapCenter memorizza il clone nella stessa posizione e nello stesso host del backup clonato.



 a| 
Posizione diversa
 a| 
È possibile memorizzare il clone in una posizione diversa sullo stesso host o su un altro host. L'host deve disporre di una connessione configurata alla macchina virtuale di storage (SVM).

|===
È possibile rinominare il clone una volta completata l'operazione.
