---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: È possibile utilizzare SnapCenter per ripristinare i backup del file system. Il ripristino del file system è un processo multifase che copia tutti i dati da un backup specificato nella posizione originale del file system. 
---
= Ripristinare i backup del file system di Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare SnapCenter per ripristinare i backup del file system. Il ripristino del file system è un processo multifase che copia tutti i dati da un backup specificato nella posizione originale del file system.

.Prima di iniziare
* È necessario aver eseguito il backup del file system.
* Se è in corso un'operazione pianificata, ad esempio un'operazione di backup, per un file system, tale operazione deve essere annullata prima di poter avviare un'operazione di ripristino.
* È possibile ripristinare solo un backup del file system nella posizione originale e non in un percorso alternativo.
+
Non è possibile ripristinare un singolo file da un backup perché il file system ripristinato sovrascrive qualsiasi dato nella posizione originale del file system. Per ripristinare un singolo file da un backup del file system, è necessario clonare il backup e accedere al file nel clone.

* Non è possibile ripristinare un volume di sistema o di avvio.
* SnapCenter può ripristinare i file system in un cluster Windows senza disattivare il gruppo di cluster.


.A proposito di questa attività
* IL PERCORSO_SCRIPT viene definito utilizzando la chiave PredesedWindowsScriptsDirectory situata nel file SMCoreServiceHost.exe.Config dell'host del plug-in.
+
Se necessario, è possibile modificare questo percorso e riavviare il servizio SMcore. Si consiglia di utilizzare il percorso predefinito per la protezione.

+
Il valore della chiave può essere visualizzato da swagger attraverso l'API: API /4.7/configsettings

+
È possibile utilizzare L'API GET per visualizzare il valore della chiave. L'API SET non è supportata.

* Per l'operazione di ripristino della sincronizzazione attiva di SnapMirror, devi selezionare il backup dalla posizione principale.
* Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli Snapshot del vault di SnapLock come parte del ripristino ereditano il tempo di scadenza del vault di SnapLock. L'amministratore dello storage dovrebbe ripulire manualmente i cloni dopo il tempo di scadenza del SnapLock.


[role="tabbed-block"]
====
.SnapCenter UI
--
.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *risorse*, quindi selezionare il plug-in appropriato dall'elenco.
. Per filtrare l'elenco delle risorse, selezionare le opzioni file system (file system) e Resource Group (Gruppo di risorse).
. Selezionare un gruppo di risorse dall'elenco, quindi fare clic su *Ripristina*.
. Nella pagina Backup, selezionare se si desidera eseguire il ripristino da sistemi di storage primari o secondari, quindi selezionare un backup da ripristinare.
. Selezionare le opzioni desiderate nella procedura guidata di ripristino.
. È possibile immettere il percorso e gli argomenti del prescrittt o del postscript che si desidera eseguire SnapCenter rispettivamente prima o dopo l'operazione di ripristino.
+
Ad esempio, è possibile eseguire uno script per aggiornare i trap SNMP, automatizzare gli avvisi, inviare i registri e così via.

+

NOTE: Il percorso prescripts o postscripts non deve includere dischi o condivisioni. Il percorso deve essere relativo al PERCORSO_SCRIPT.

. Nella pagina Notification (notifica), selezionare una delle seguenti opzioni:
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Registrare gli eventi del server SnapCenter nel syslog del sistema di storage
 a| 
Selezionare questa opzione per registrare gli eventi del server SnapCenter nel syslog del sistema di storage.



 a| 
Invia al sistema di storage la notifica AutoSupport per le operazioni non riuscite
 a| 
Selezionare questa opzione per inviare a NetApp informazioni su operazioni non riuscite utilizzando AutoSupport.



 a| 
Preferenza e-mail
 a| 
Selezionare *Always*, *on Failure* o *on failure or warning* per inviare messaggi e-mail ai destinatari dopo il ripristino dei backup. Immettere il server SMTP, l'oggetto e-mail predefinito e gli indirizzi e-mail a e da.

|===
. Esaminare il riepilogo, quindi fare clic su *fine*.
. Monitorare l'avanzamento dell'operazione facendo clic su *Monitor* > *Jobs*.



IMPORTANT: Se il file system ripristinato contiene un database, è necessario ripristinarlo. Se il database non viene ripristinato, potrebbe essere in uno stato non valido. Per informazioni sul ripristino dei database, consultare la Data Protection Guide relativa al database.

--
.Cmdlet PowerShell
--
.Fasi
. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
PS C:\> Open-Smconnection
----
. Recuperare le informazioni relative a uno o più backup che si desidera ripristinare utilizzando i cmdlet Get-SmBackup e Get-SmBackupReport.
+
Questo esempio mostra informazioni su tutti i backup disponibili:

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
Questo esempio mostra informazioni dettagliate sul backup dal 29 gennaio 2015 al 3 febbraio 2015:

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Ripristinare i dati dal backup utilizzando il cmdlet Restore-SmBackup.
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento anche a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento al cmdlet del software SnapCenter"^].

--
====