---
permalink: protect-scw/task_import_CA_certificates.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Importare i certificati CA del server SnapCenter e i plug-in host di Windows 
---
= Importare i certificati CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario importare i certificati CA nel server SnapCenter e nei plug-in host di Windows utilizzando la console di gestione Microsoft (MMC).

*Fasi*

. Accedere alla console di gestione Microsoft (MMC), quindi fare clic su *file* > *Aggiungi/Rimuovi Snapin*.
. Nella finestra Aggiungi o Rimuovi snap-in, selezionare *certificati*, quindi fare clic su *Aggiungi*.
. Nella finestra dello snap-in certificati, selezionare l'opzione *account computer*, quindi fare clic su *fine*.
. Fare clic su *root console* > *certificati – computer locale* > *autorità di certificazione root attendibili* > *certificati*.
. Fare clic con il pulsante destro del mouse sulla cartella "Trusted Root Certification Authorities", quindi selezionare *All Tasks* > *Import* per avviare l'importazione guidata.
. Completare la procedura guidata come segue:
+
|===
| In questa finestra della procedura guidata... | Effettuare le seguenti operazioni... 


 a| 
Importa chiave privata
 a| 
Selezionare l'opzione *Sì*, importare la chiave privata, quindi fare clic su *Avanti*.



 a| 
Formato del file di importazione
 a| 
Non apportare modifiche; fare clic su *Avanti*.



 a| 
Sicurezza
 a| 
Specificare la nuova password da utilizzare per il certificato esportato, quindi fare clic su *Avanti*.



 a| 
Completamento dell'importazione guidata certificati
 a| 
Esaminare il riepilogo, quindi fare clic su *fine* per avviare l'importazione.

|===
+

NOTE: Il certificato di importazione deve essere fornito in bundle con la chiave privata (i formati supportati sono: *.pfx, *.p12 e *.p7b).

. Ripetere il passaggio 5 per la cartella "Personal".

