---
permalink: protect-scw/task_remove_backups_using_powershell_cmdlets_for_windows.html 
sidebar: sidebar 
keywords: backups 
summary: È possibile utilizzare il cmdlet Remove-SmBackup per eliminare i backup se non sono più necessari per altre operazioni di protezione dei dati. 
---
= Rimuovere i backup utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il cmdlet Remove-SmBackup per eliminare i backup se non sono più necessari per altre operazioni di protezione dei dati.

È necessario aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.

Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].

*Fasi*

. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Eliminare uno o più backup utilizzando il cmdlet Remove-SmBackup.
+
Questo esempio elimina due backup utilizzando i relativi ID di backup:

+
[listing]
----
Remove-SmBackup -BackupIds 3,4
Remove-SmBackup
Are you sure want to remove the backup(s).
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
----

