---
permalink: protect-scw/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: 'È necessario creare una connessione SVM (Storage Virtual Machine) e una credenziale prima di utilizzare i cmdlet PowerShell per eseguire operazioni di protezione dei dati.' 
---
= Creare una connessione al sistema storage e una credenziale utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare una connessione SVM (Storage Virtual Machine) e una credenziale prima di utilizzare i cmdlet PowerShell per eseguire operazioni di protezione dei dati.

*Cosa ti serve*

* L'ambiente PowerShell dovrebbe essere stato preparato per l'esecuzione dei cmdlet PowerShell.
* Per creare le connessioni storage, è necessario disporre delle autorizzazioni necessarie nel ruolo Infrastructure Admin.
* Assicurarsi che le installazioni dei plug-in non siano in corso.
+
Le installazioni dei plug-in host non devono essere in corso durante l'aggiunta di una connessione al sistema di storage perché la cache host potrebbe non essere aggiornata e lo stato dei database potrebbe essere visualizzato nella GUI di SnapCenter come "`non disponibile per il backup`" o "`non su storage NetApp`".

* I nomi dei sistemi di storage devono essere univoci.
+
SnapCenter non supporta più sistemi storage con lo stesso nome su cluster diversi. Ogni sistema storage supportato da SnapCenter deve avere un nome univoco e un indirizzo IP LIF di gestione univoco.



*Fasi*

. Avviare una sessione di connessione PowerShell utilizzando il cmdlet Open-SmConnection.
+
Questo esempio apre una sessione PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Creare una nuova connessione al sistema di storage utilizzando il cmdlet Add-SmStorageConnection.
+
Questo esempio crea una nuova connessione al sistema di storage:

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Creare una nuova credenziale utilizzando il cmdlet Add-SmCredential.
+
In questo esempio viene creata una nuova credenziale denominata FinanceAdmin con credenziali Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].
