---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server 
summary: È possibile utilizzare il file eseguibile del programma di installazione del server SnapCenter per aggiornare il server SnapCenter. 
---
= Aggiornare il server SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il file eseguibile del programma di installazione del server SnapCenter per aggiornare il server SnapCenter.

*Cosa ti serve*

* L'host del server SnapCenter deve essere aggiornato con gli aggiornamenti di Windows, senza riavvii del sistema in sospeso.
* Prima di iniziare l'operazione di aggiornamento, assicurarsi che non siano in esecuzione altre operazioni.
* È necessario eseguire il backup del database del repository SnapCenter (MySQL) dopo aver eseguito tutti i processi. Si consiglia di eseguire l'aggiornamento del server SnapCenter e del plug-in Exchange.
+
Per ulteriori informazioni, vedere link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Eseguire il backup del repository SnapCenter"^].

* Eseguire il backup di tutti i file di configurazione SnapCenter modificati sull'host del server SnapCenter o sul plug-in host.
+
Esempi di file di configurazione di SnapCenter: SnapDriveService.exe.config, SMCoreServiceHost.exe.config e così via.



*A proposito di questa attività*

* Durante l'aggiornamento, l'host viene automaticamente messo in modalità di manutenzione che impedisce all'host di eseguire qualsiasi processo pianificato. Dopo l'aggiornamento, l'host viene automaticamente disattivato dalla modalità di manutenzione.
* Durante l'aggiornamento, viene eseguito uno script SQL per aggiornare i dati di Exchange nel database NSM, che converte il DAG e il shortname host in FQDN. Questa opzione è applicabile solo se si utilizza il server SnapCenter con il plug-in Exchange.
* Prima di iniziare l'operazione di aggiornamento, se l'host è stato impostato manualmente in modalità di manutenzione, dopo l'aggiornamento è necessario disattivare manualmente la modalità di manutenzione dell'host facendo clic su *host* > *attiva pianificazione*.
* Per il plug-in SnapCenter per Microsoft SQL Server, il plug-in SnapCenter per Microsoft Exchange Server e il plug-in SnapCenter per Microsoft Windows, si consiglia di aggiornare sia il server che gli host dei plug-in alla versione 4.7 affinché IL PERCORSO SCRIPT venga eseguito.
+
Per le pianificazioni di backup e verifica esistenti con prescritture e postscript attivati nel criterio, le operazioni di backup continueranno a funzionare dopo l'aggiornamento.

+
Nella pagina *Dettagli lavoro*, un messaggio di avviso consiglia al cliente di copiare gli script nel PERCORSO_SCRIPT e modificare il criterio per fornire un percorso relativo al PERCORSO_SCRIPT. Per il lavoro del ciclo di vita clone, il messaggio di avviso viene visualizzato a livello di lavoro secondario.



*Fasi*

. Scaricare il pacchetto di installazione del server SnapCenter dal sito del supporto NetApp.
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. Creare una copia del file web.config che si trova in C: File di programma NetApp SnapCenter WebApp.
. Esportare le pianificazioni SnapCenter relative all'host plug-in dalla pianificazione delle attività di Windows in modo da poterle utilizzare per ripristinare le pianificazioni in caso di errore nell'aggiornamento.
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. Creare il dump del database MySQL SnapCenter se il backup del repository non è configurato.
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
Quando richiesto, inserire la password.

. Avviare l'aggiornamento del server SnapCenter facendo doppio clic sul file .exe scaricato.
+
Una volta avviato l'aggiornamento, vengono eseguiti tutti i controlli preliminari e, se i requisiti minimi non vengono soddisfatti, vengono visualizzati i messaggi di errore o di avviso appropriati. È possibile ignorare i messaggi di avviso e procedere con l'installazione. Tuttavia, gli errori devono essere corretti.

+

NOTE: SnapCenter continuerà a utilizzare la password esistente del database del repository MySQL Server fornita durante l'installazione della versione precedente del server SnapCenter.

. Fare clic su *Upgrade* (Aggiorna).
+
In qualsiasi momento, facendo clic sul pulsante *Annulla*, il flusso di lavoro di aggiornamento viene annullato. Non ripristinerà lo stato precedente del server SnapCenter.

+
|===


| *Procedura consigliata:* per accedere all'interfaccia grafica di SnapCenter, è necessario disconnettersi e accedere a SnapCenter oppure chiudere e aprire un nuovo browser. 
|===


*Al termine*

* Se il plug-in viene installato utilizzando un utente sudo, copiare le chiavi sha224 disponibili in _C: ProgramData/NetApp/SnapCenter/Package Repository/oracle_checksum.txt_ per aggiornare il file _/etc/sudoers_.
* È necessario eseguire un nuovo rilevamento delle risorse sugli host.
+
Se lo stato dell'host viene visualizzato come interrotto, è possibile attendere qualche istante ed eseguire una nuova ricerca. È inoltre possibile modificare il valore del parametro *HostRefreshInterval* (il valore predefinito è 3600 secondi) su un valore superiore a 10 minuti.

* Se l'aggiornamento non riesce, è necessario eliminare l'installazione non riuscita, reinstallare la versione precedente di SnapCenter e ripristinare il database NSM allo stato precedente.
* Dopo aver aggiornato l'host del server SnapCenter, è necessario aggiornare i plug-in prima di aggiungere qualsiasi sistema di storage.

