---
permalink: upgrade/task_configure_snapcenter_to_check_for_available_updates.html 
sidebar: sidebar 
keywords: configure, snapcenter server, updates, software updates 
summary: 'SnapCenter comunica periodicamente con il sito di supporto NetApp per notificare gli aggiornamenti software disponibili. È inoltre possibile creare una pianificazione per specificare l"intervallo in cui si desidera ricevere informazioni sugli aggiornamenti disponibili.' 
---
= Configurare SnapCenter per verificare la disponibilità di aggiornamenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter comunica periodicamente con il sito di supporto NetApp per notificare gli aggiornamenti software disponibili. È inoltre possibile creare una pianificazione per specificare l'intervallo in cui si desidera ricevere informazioni sugli aggiornamenti disponibili.

.Fasi
. Nel riquadro di navigazione a sinistra, selezionare *Impostazioni*.
. Nella pagina *Impostazioni*, selezionare *Software*.
+
La pagina Software disponibile visualizza i pacchetti plug-in disponibili, le versioni disponibili e il relativo stato di installazione.

. Seleziona *Verifica aggiornamenti* per vedere se sono disponibili versioni più recenti dei pacchetti di plug-in.
. Seleziona *Pianifica aggiornamenti* per creare una pianificazione per specificare l'intervallo in cui desideri ricevere informazioni sugli aggiornamenti disponibili:
+
.. Selezionare l'intervallo in *Controlla aggiornamenti*.
.. Selezionare la credenziale di amministrazione del server SnapCenter e fare clic su *OK*.



