---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: Prima di aggiungere un host e installare i pacchetti plug-in, è necessario completare tutti i requisiti. Il plug-in SnapCenter per database SAP HANA è disponibile sia in ambienti Windows che Linux. 
---
= Prerequisiti per l'aggiunta di host e l'installazione del plug-in SnapCenter per il database SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiungere un host e installare i pacchetti plug-in, è necessario completare tutti i requisiti. Il plug-in SnapCenter per database SAP HANA è disponibile sia in ambienti Windows che Linux.

* È necessario aver installato Java 11 sull'host.
+

NOTE: IBM Java non è supportato.

* È necessario aver installato il terminale interattivo del database SAP HANA (client HDBSQL) sull'host.
* Per Windows, il servizio di creazione del plug-in deve essere eseguito utilizzando l'utente di Windows "`LocalSystem`", che è il comportamento predefinito quando il plug-in per il database SAP HANA viene installato come amministratore di dominio.
* Per Windows, le chiavi dell'archivio utente devono essere create come utente DI SISTEMA.
* Quando si installa un plug-in su un host Windows, se si specifica una credenziale non integrata o se l'utente appartiene a un utente del gruppo di lavoro locale, è necessario disattivare il controllo dell'account utente sull'host. Il plug-in SnapCenter per Microsoft Windows verrà implementato per impostazione predefinita con il plug-in SAP HANA sugli host Windows.
* Per l'host Linux, le chiavi HDB Secure User Store sono accessibili come utente del sistema operativo HDBSQL.
* Il server SnapCenter deve avere accesso alla porta 8145 o alla porta personalizzata del plug-in per l'host del database SAP HANA.




== Host Windows

* È necessario disporre di un utente di dominio con privilegi di amministratore locale con autorizzazioni di accesso locale sull'host remoto.
* Durante l'installazione del plug-in per database SAP HANA su un host Windows, il plug-in SnapCenter per Microsoft Windows viene installato automaticamente.
* È necessario aver attivato la connessione SSH basata su password per l'utente root o non root.
* È necessario aver installato Java 11 sull'host Windows.
+
http://www.java.com/en/download/manual.jsp["Download Java per tutti i sistemi operativi"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"]





== Host Linux

* È necessario aver attivato la connessione SSH basata su password per l'utente root o non root.
* È necessario aver installato Java 11 sull'host Linux.
+
http://www.java.com/en/download/manual.jsp["Download Java per tutti i sistemi operativi"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"]

* Per i database SAP HANA in esecuzione su un host Linux, durante l'installazione del plug-in per il database SAP HANA, il plug-in SnapCenter per UNIX viene installato automaticamente.
* Si dovrebbe avere *bash* come shell predefinita per l'installazione del plug-in.




== Comandi supplementari

Per eseguire un comando supplementare sul plug-in SnapCenter per SAP HANA, è necessario includerlo nel file _allowed_Commands.config_.

* Posizione predefinita sull'host Windows: _C:\programmi\NetApp\SnapCenter\SnapCenter Plug-in Creator\etc\allowed_Commands.config_
* Posizione predefinita sull'host Linux: _/opt/NetApp/SnapCenter/scc/etc/allowed_Commands.config_


Per consentire comandi supplementari sull'host del plug-in, aprire il file _allowed_Commands.config_ in un editor. Immettere ciascun comando su una riga separata; i comandi non rilevano la distinzione tra maiuscole e minuscole. Assicurarsi di specificare il percorso completo e racchiudere il percorso tra virgolette (") se contiene spazi.

Ad esempio:

comando: mount

comando: umount

Comando: "C:\Program Files\NetApp\SnapCreator Commands\sdcli.exe"

comando: myscript.bat

Se il file _allowed_Commands.config_ non è presente, i comandi o l'esecuzione dello script verranno bloccati e il flusso di lavoro non riuscirà con il seguente errore:

"[/mnt/mount -a] esecuzione non consentita. Autorizzare aggiungendo il comando nel file %s sull'host del plugin."

Se il comando o lo script non è presente in _allowed_Commands.config_, l'esecuzione del comando o dello script verrà bloccata e il flusso di lavoro non riuscirà con il seguente errore:

"[/mnt/mount -a] esecuzione non consentita. Autorizzare aggiungendo il comando nel file %s sull'host del plugin."


NOTE: Non utilizzare un carattere jolly (*) per consentire tutti i comandi.



== Configurare i privilegi sudo per gli utenti non root per l'host Linux

SnapCenter 2.0 e versioni successive consentono a un utente non root di installare il pacchetto di plug-in SnapCenter per Linux e avviare il processo di plug-in. I processi di plug-in verranno eseguiti come utenti non root. È necessario configurare i privilegi sudo per l'utente non root per fornire l'accesso a diversi percorsi.

*Cosa ti serve*

* Sudo versione 1.8.7 o successiva.
* Se l'umask è 0027, assicurarsi che la cartella java e tutti i file all'interno dovrebbero avere l'autorizzazione di 555. In caso contrario, l'installazione dei plug-in potrebbe non riuscire.
* Per l'utente non root, assicurarsi che il nome dell'utente non root e del gruppo dell'utente siano identici.
* Modificare il file _/etc/ssh/sshd_config_ per configurare gli algoritmi del codice di autenticazione del messaggio: Mac hmac-sha2-256 e Mac hmac-sha2-512.
+
Riavviare il servizio sshd dopo aver aggiornato il file di configurazione.

+
Esempio:

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*A proposito di questa attività*

È necessario configurare i privilegi sudo per l'utente non root per fornire l'accesso ai seguenti percorsi:

* /Home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin
* /Custom_location/NetApp/snapcenter/spl/installation/plugins/uninstall
* /Custom_location/NetApp/snapcenter/spl/bin/spl


*Fasi*

. Accedere all'host Linux su cui si desidera installare il pacchetto di plug-in SnapCenter per Linux.
. Aggiungere le seguenti righe al file /etc/sudoers usando l'utility visudo Linux.
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+

NOTE: Se si dispone di una configurazione RAC, insieme agli altri comandi consentiti, aggiungere quanto segue al file /etc/sudoers: '/<crs_home>/bin/olsnodes'



È possibile ottenere il valore di _crs_home_ dal file _/etc/oracle/olr.loc_.

_LINUX_USER_ è il nome dell'utente non root creato.

È possibile ottenere il _checksum_value_ dal file *sc_unix_plugins_checksum.txt*, che si trova in:

* _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ se il server SnapCenter è installato sull'host Windows.
* _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ se il server SnapCenter è installato sull'host Linux. .



IMPORTANT: L'esempio deve essere utilizzato solo come riferimento per la creazione di dati personali.
