---
permalink: protect-hana/reference_host_requirements_to_install_snapcenter_plug_in_package_for_windows_hana.html 
sidebar: sidebar 
keywords: SAP HANA,Custom plug-ins 
summary: Prima di installare il pacchetto di plug-in SnapCenter per Windows, è necessario conoscere alcuni requisiti di base relativi allo spazio del sistema host e al dimensionamento. 
---
= Requisiti dell'host per installare il pacchetto di plug-in SnapCenter per Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il pacchetto di plug-in SnapCenter per Windows, è necessario conoscere alcuni requisiti di base relativi allo spazio del sistema host e al dimensionamento.

|===
| Elemento | Requisiti 


 a| 
Sistemi operativi
 a| 
Microsoft Windows

Per informazioni aggiornate sulle versioni supportate, vedere https://imt.netapp.com/imt/imt.jsp?components=134502;&solution=1258&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].



 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
1 GB



 a| 
Spazio minimo di installazione e registrazione per il plug-in SnapCenter sull'host
 a| 
5 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di storage da parte della cartella dei log. Lo spazio di log richiesto varia in base al numero delle entità da proteggere e alla frequenza delle operazioni di protezione dei dati. Se lo spazio su disco non è sufficiente, i registri non verranno creati per le operazioni eseguite di recente.



 a| 
Pacchetti software richiesti
 a| 
* ASP.NET Core Runtime 8.0.12 (e tutte le successive patch 8,0.x) Hosting Bundle
* PowerShell Core 7.4.2
* Java 11 Oracle Java e OpenJDK
+
Java 11 Oracle Java e OpenJDK sono necessari solo per i plug-in supportati da SAP HANA, IBM DB2, PostgreSQL, MySQL, NetApp e altre applicazioni personalizzate che possono essere installate sull'host Windows.



Per informazioni aggiornate sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].

Per informazioni specifiche sulla risoluzione dei problemi di .NET, vedere https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["L'aggiornamento o l'installazione di SnapCenter non riesce per i sistemi legacy che non dispongono di connettività Internet."]

|===