---
permalink: protect-hana/task_restore_sap_hana_database_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore 
summary: 'Il ripristino di un backup del database SAP HANA include l"avvio di una sessione di connessione con il server SnapCenter, l"elenco dei backup e il recupero delle informazioni di backup e il ripristino di un backup.' 
---
= Ripristinare il database SAP HANA utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ripristino di un backup del database SAP HANA include l'avvio di una sessione di connessione con il server SnapCenter, l'elenco dei backup e il recupero delle informazioni di backup e il ripristino di un backup.

*Cosa ti serve*

È necessario aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.

*Fasi*

. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Identificare il backup che si desidera ripristinare utilizzando i cmdlet Get-SmBackup e Get-SmBackupReport.
+
Questo esempio mostra che sono disponibili due backup per il ripristino:

+
[listing]
----
 PS C:\> Get-SmBackup

        BackupId    BackupName                    BackupTime            BackupType
        --------    ----------                    ----------            ----------
         1          Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM  Full Backup
         2          Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
+
Questo esempio mostra informazioni dettagliate sul backup dal 29 gennaio 2015 al 3 febbraio 2015:

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Avviare il processo di ripristino in HANA Studio.
+
Il database viene chiuso.

. Ripristinare i dati dal backup utilizzando il cmdlet Restore-SmBackup.
+

NOTE: AppObjectId è "host/Plugin/UID", dove UID = SID è per la risorsa di tipo container singolo e UID = MDC/SID è per la risorsa di container multipli. È possibile ottenere ResourceID dal cmdlet Get-smResources.

+
[listing]
----
Get-smResources  -HostName cn24.sccore.test.com  -PluginCode HANA
----
+
Questo esempio mostra come ripristinare il database dallo storage primario:

+
[listing]
----
Restore-SmBackup -PluginCode HANA -AppObjectId cn24.sccore.test.com\hana\H10 -BackupId 3
----
+
Questo esempio mostra come ripristinare il database dallo storage secondario:

+
[listing]
----
Restore-SmBackup -PluginCode 'HANA' -AppObjectId cn24.sccore.test.com\hana\H10 -BackupId 399 -Confirm:$false  -Archive @( @{"Primary"="<Primary Vserver>:<PrimaryVolume>";"Secondary"="<Secondary Vserver>:<SecondaryVolume>"})
----
+
I backup saranno disponibili in HANA Studio per il recovery.



Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].
