---
permalink: protect-scc/concept_develop_a_plug_in_for_your_application.html 
sidebar: sidebar 
keywords:  
summary: Il server SnapCenter consente di implementare e gestire le applicazioni come plug-in per SnapCenter. 
---
= Panoramica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il server SnapCenter consente di implementare e gestire le applicazioni come plug-in per SnapCenter. È possibile collegare al server SnapCenter applicazioni di vostra scelta per la protezione e la gestione dei dati.

SnapCenter consente di sviluppare plug-in personalizzati utilizzando diversi linguaggi di programmazione. È possibile sviluppare un plug-in personalizzato utilizzando Perl, Java, BATCH o altri linguaggi di scripting.

Per utilizzare plug-in personalizzati in SnapCenter, è necessario eseguire le seguenti operazioni:

* Creare un plug-in per l'applicazione seguendo le istruzioni di questa guida
* Creare un file di descrizione
* Esportare il plug-in personalizzato per installarlo sull'host SnapCenter
* Caricare il file zip del plug-in nel server SnapCenter




== Gestione di plug-in generici in tutte le chiamate API

Per ogni chiamata API, utilizzare le seguenti informazioni:

* Parametri del plug-in
* Codici di uscita
* Registrare i messaggi di errore
* Coerenza dei dati




=== Utilizzare i parametri del plug-in

Un insieme di parametri viene passato al plug-in come parte di ogni chiamata API effettuata. La seguente tabella elenca le informazioni specifiche per i parametri.

|===
| Parametro | Scopo 


 a| 
AZIONE
 a| 
Determina il nome del flusso di lavoro. Ad esempio, Discover, backup, fileOrVolRestore o cloneVolAndLun



 a| 
RISORSE
 a| 
Elenca le risorse da proteggere. Una risorsa è identificata da UID e Type. L'elenco viene presentato al plug-in nel seguente formato:

"<UID>,<TYPE>;<UID>,<TYPE>". Ad esempio, "Instance1,Instance;Instance2,DB1,Database"



 a| 
NOME_APP
 a| 
Determina quale plug-in viene utilizzato. Ad esempio, DB2, MYSQL. Il server SnapCenter dispone di un supporto integrato per le applicazioni elencate. Questo parametro fa distinzione tra maiuscole e minuscole.



 a| 
APP_IGNORE_ERROR
 a| 
(Y o N) questo causa l'uscita di SnapCenter quando si verifica un errore dell'applicazione. Ciò è utile quando si esegue il backup di più database e non si desidera che un singolo errore interrompa l'operazione di backup.



 a| 
<RESOURCE_NAME>__APP_INSTANCE_USERNAME
 a| 
La credenziale SnapCenter è impostata per la risorsa.



 a| 
<RESOURCE_NAME>_APP_INSTANCE_PASSWORD
 a| 
La credenziale SnapCenter è impostata per la risorsa.



 a| 
<RESOURCE_NAME>_<CUSTOM_PARAM>
 a| 
Ogni valore della chiave personalizzata a livello di risorsa è disponibile per i plug-in con prefisso "<RESOURCE_NAME>_". Ad esempio, se una chiave personalizzata è "MASTER_SLAVE" per una risorsa denominata "MySQLDB", sarà disponibile come MySQLDB_MASTER_SLAVE

|===


=== Utilizzare i codici di uscita

Il plug-in restituisce lo stato dell'operazione all'host mediante i codici di uscita. Ciascun codice ha un significato specifico e il plug-in utilizza il codice di uscita corretto per indicare lo stesso.

La tabella seguente illustra i codici di errore e il relativo significato.

|===
| Codice di uscita | Scopo 


 a| 
0
 a| 
Operazione riuscita.



 a| 
99
 a| 
L'operazione richiesta non è supportata o implementata.



 a| 
100
 a| 
Operazione non riuscita, ignorare e uscire. Unquiesce è per impostazione predefinita.



 a| 
101
 a| 
Operazione non riuscita, continuare con l'operazione di backup.



 a| 
altro
 a| 
Operazione non riuscita, eseguire senza problemi e uscire.

|===


=== Registrare i messaggi di errore

I messaggi di errore vengono passati dal plug-in al server SnapCenter. Il messaggio include il messaggio, il livello di registrazione e l'indicazione dell'ora.

La tabella seguente elenca i livelli e i relativi scopi.

|===
| Parametro | Scopo 


 a| 
INFO
 a| 
messaggio informativo



 a| 
ATTENZIONE
 a| 
messaggio di avviso



 a| 
ERRORE
 a| 
messaggio di errore



 a| 
DEBUG
 a| 
messaggio di debug



 a| 
TRACCIA
 a| 
messaggio di traccia

|===


=== Preservare la coerenza dei dati

I plug-in personalizzati mantengono i dati tra le operazioni della stessa esecuzione del workflow. Ad esempio, un plug-in può memorizzare i dati alla fine di quiesce, che possono essere utilizzati durante un'operazione senza problemi.

I dati da conservare vengono impostati come parte dell'oggetto risultato tramite plug-in. Segue un formato specifico ed è descritto in dettaglio in ogni stile di sviluppo del plug-in.
