---
permalink: protect-scc/reference_types_of_restore_strategies_supported_for_manually_added_custom_plugin_resources.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: È necessario definire una strategia prima di poter eseguire correttamente le operazioni di ripristino utilizzando SnapCenter. Esistono due tipi di strategie di ripristino per le risorse plug-in personalizzate aggiunte manualmente. Non è possibile ripristinare le risorse plug-in personalizzate aggiunte manualmente. 
---
= Tipi di strategie di ripristino supportate per risorse plug-in personalizzate aggiunte manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario definire una strategia prima di poter eseguire correttamente le operazioni di ripristino utilizzando SnapCenter. Esistono due tipi di strategie di ripristino per le risorse plug-in personalizzate aggiunte manualmente.


NOTE: Non è possibile ripristinare le risorse plug-in personalizzate aggiunte manualmente.



== Ripristino completo delle risorse

* Ripristina tutti i volumi, le qtree e le LUN di una risorsa



NOTE: Se la risorsa contiene volumi o qtree, le copie Snapshot eseguite dopo la copia Snapshot selezionata per il ripristino su tali volumi o qtree vengono eliminate e non possono essere ripristinate. Inoltre, se un'altra risorsa è ospitata sugli stessi volumi o qtree, anche tale risorsa viene eliminata.



== Ripristino a livello di file

* Ripristina i file da volumi, qtree o directory
* Ripristina solo i LUN selezionati

