---
permalink: protect-scc/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux_scc.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Assicurarsi che l"host soddisfi i requisiti prima di installare il pacchetto di plug-in SnapCenter per Linux.' 
---
= Requisiti dell'host per l'installazione del pacchetto di plug-in SnapCenter per Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Assicurarsi che l'host soddisfi i requisiti prima di installare il pacchetto di plug-in SnapCenter per Linux.

|===
| Elemento | Requisiti 


 a| 
Sistemi operativi
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
1 GB



 a| 
Spazio minimo di installazione e registrazione per il plug-in SnapCenter sull'host
 a| 
2 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di storage da parte della cartella dei log. Lo spazio di log richiesto varia in base al numero delle entità da proteggere e alla frequenza delle operazioni di protezione dei dati. Se lo spazio su disco non è sufficiente, i registri non verranno creati per le operazioni eseguite di recente.



 a| 
Pacchetti software richiesti
 a| 
Java 1.8 (64 bit) Oracle Java o OpenJDK Flavors

Se JAVA è stato aggiornato alla versione più recente, assicurarsi che l'opzione JAVA_HOME disponibile in /var/opt/snapcenter/spl/etc/spl.properties sia impostata sulla versione JAVA corretta e sul percorso corretto.

|===
Per informazioni aggiornate sulle versioni supportate, consultare https://imt.netapp.com/matrix/imt.jsp?components=108393;&solution=1259&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"]
