---
permalink: protect-scc/task_back_up_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords:  
summary: 'Il backup di una risorsa include la connessione con il server SnapCenter, l"aggiunta di risorse, l"aggiunta di un criterio, la creazione di un gruppo di risorse di backup e il backup.' 
---
= Eseguire il backup delle risorse utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il backup di una risorsa include la connessione con il server SnapCenter, l'aggiunta di risorse, l'aggiunta di un criterio, la creazione di un gruppo di risorse di backup e il backup.

*Cosa ti serve*

* È necessario aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.
* È necessario aver aggiunto la connessione al sistema di storage e creato una credenziale.


*A proposito di questa attività*

Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].

*Fasi*

. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146\
----
+
Viene visualizzato il prompt di nome utente e password.

. Aggiungere risorse utilizzando il cmdlet Add-SmResources.
+
Questo esempio aggiunge risorse:

+
[listing]
----
Add-SmResource -HostName '10.232.206.248' -PluginCode 'DB2' -ResourceName NONREC1 -ResourceType Database -StorageFootPrint ( @
{"VolumeName"="DB2_NONREC1DB";"LunName"="DB2_NONREC1DB";"Vserver"="vserver_scauto_secondary"}) -Instance db2inst1
----
. Creare un criterio di backup utilizzando il cmdlet Add-SmPolicy.
+
Questo esempio crea una nuova policy di backup:

+
[listing]
----
Add-SMPolicy -PolicyName 'db2VolumePolicy' -PolicyType 'Backup' -PluginPolicyType DB2  -description 'VolumePolicy'
----
. Aggiungere un nuovo gruppo di risorse a SnapCenter utilizzando il cmdlet Add-SmResourceGroup.
+
In questo esempio viene creato un nuovo gruppo di risorse con le risorse e i criteri specificati:

+
[listing]
----
Add-SmResourceGroup -ResourceGroupName 'Verify_ManualBackup_DatabaseLevel_MultipleVolume_unix' -Resources @(@
{"Host"="10.232.206.248";"Uid"="db2inst2\NONREC"},@{"Host"="10.232.206.248";"Uid"="db2inst1\NONREC"}) -Policies db2ManualPolicy
----
. Avviare un nuovo processo di backup utilizzando il cmdlet New-SmBackup.
+
[listing]
----
New-SMBackup -DatasetName Verify_ManualBackup_DatabaseLevel_MultipleVolume_unix -Policy db2ManualPolicy
----
. Visualizzare lo stato del processo di backup utilizzando il cmdlet Get-SmBackupReport.
+
Questo esempio visualizza un report di riepilogo di tutti i lavori eseguiti alla data specificata:

+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----

