---
permalink: protect-scc/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html 
sidebar: sidebar 
keywords: credentials 
summary: Utilizzare la pagina SnapCenterAdd host per aggiungere host e installare i pacchetti plug-in. I plug-in vengono installati automaticamente sugli host remoti. È possibile aggiungere un host e installare i pacchetti plug-in per un singolo host o per un cluster. 
---
= Aggiungere host e installare pacchetti plug-in su host remoti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare la pagina SnapCenterAdd host per aggiungere host e installare i pacchetti plug-in. I plug-in vengono installati automaticamente sugli host remoti. È possibile aggiungere un host e installare i pacchetti plug-in per un singolo host o per un cluster.

*Cosa ti serve*

* Si dovrebbe essere un utente assegnato a un ruolo che dispone delle autorizzazioni di installazione e disinstallazione del plug-in, ad esempio il ruolo di amministratore di SnapCenter.
* Assicurarsi che il servizio di accodamento dei messaggi sia in esecuzione.
* Se si utilizza un account di servizio gestito di gruppo (gMSA), è necessario configurare gMSA con privilegi amministrativi.
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Configurare l'account di servizio gestito di gruppo su Windows Server 2012 o versione successiva per le applicazioni personalizzate"]



*A proposito di questa attività*

Non è possibile aggiungere un server SnapCenter come host plug-in a un altro server SnapCenter.

Se si installano plug-in su un cluster (WSFC), i plug-in vengono installati su tutti i nodi del cluster.

*Fasi*

. Nel riquadro di spostamento di sinistra, fare clic su *hosts*.
. Verificare che la scheda *Managed hosts* sia selezionata nella parte superiore.
. Fare clic su *Aggiungi*.
. Nella pagina host, eseguire le seguenti operazioni:
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Tipo di host
 a| 
Selezionare il tipo di host:

** Windows
** Linux



NOTE: I plug-in personalizzati possono essere utilizzati in ambienti Windows e Linux.



 a| 
Nome host
 a| 
Inserire il nome di dominio completo (FQDN) o l'indirizzo IP dell'host.

SnapCenter dipende dalla configurazione corretta del DNS. Pertanto, la procedura consigliata consiste nell'inserire l'FQDN.

Per gli ambienti Windows, l'indirizzo IP è supportato per gli host di dominio non attendibili solo se viene risolto nell'FQDN.

È possibile inserire gli indirizzi IP o il nome FQDN di un host standalone.

Se si aggiunge un host utilizzando SnapCenter e l'host fa parte di un sottodominio, è necessario fornire l'FQDN.



 a| 
Credenziali
 a| 
Selezionare il nome della credenziale creata o creare nuove credenziali.

Le credenziali devono disporre di diritti amministrativi sull'host remoto. Per ulteriori informazioni, vedere le informazioni sulla creazione delle credenziali.

È possibile visualizzare i dettagli relativi alle credenziali posizionando il cursore sul nome specificato.


NOTE: La modalità di autenticazione delle credenziali è determinata dal tipo di host specificato nella procedura guidata Aggiungi host.

|===
. Nella sezione *Seleziona plug-in da installare*, selezionare i plug-in da installare.
. (Facoltativo) fare clic su *altre opzioni*.
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Porta
 a| 
Mantenere il numero di porta predefinito oppure specificare il numero di porta.

Il numero di porta predefinito è 8145. Se il server SnapCenter è stato installato su una porta personalizzata, tale numero di porta viene visualizzato come porta predefinita.


NOTE: Se i plug-in sono stati installati manualmente e si è specificata una porta personalizzata, è necessario specificare la stessa porta. In caso contrario, l'operazione non riesce.



 a| 
Percorso di installazione
 a| 
I plug-in personalizzati possono essere installati su un sistema Windows o Linux.

** Per il pacchetto di plug-in SnapCenter per Windows, il percorso predefinito è C:
+
In alternativa, è possibile personalizzare il percorso.

** Per il pacchetto di plug-in SnapCenter per Linux, il percorso predefinito è /opt/NetApp/snapcenter.
+
In alternativa, è possibile personalizzare il percorso.

** Per i plug-in personalizzati di SnapCenter:
+
... Nella sezione Custom Plug-in (Plug-in personalizzati), fare clic su *Browse* (Sfoglia) e selezionare la cartella dei plug-in personalizzati compressi.
+
La cartella zippata contiene il codice del plug-in personalizzato e il file .xml descrittore.

+
Per Storage Plug-in, accedere a _C:/ProgramData/NetApp/SnapCenter/Package Repository_ e selezionare `Storage.zip` cartella.

... Fare clic su *carica*.
+
Il file .xml descrittore nella cartella dei plug-in personalizzati compressi viene validato prima del caricamento del pacchetto.

+
Vengono elencati i plug-in personalizzati caricati sul server SnapCenter.

+
Se si desidera gestire applicazioni MySQL o DB2, è possibile utilizzare i plug-in personalizzati MySQL e DB2 forniti da NetApp. I plug-in personalizzati MySQL e DB2 sono disponibili sul sito https://automationstore.netapp.com/home.shtml["NetApp Automation Store"]







 a| 
Ignorare i controlli di preinstallazione
 a| 
Selezionare questa casella di controllo se i plug-in sono già stati installati manualmente e non si desidera verificare se l'host soddisfa i requisiti per l'installazione del plug-in.



 a| 
Utilizzare l'account di servizio gestito di gruppo (gMSA) per eseguire i servizi plug-in
 a| 
Per l'host Windows, selezionare questa casella di controllo se si desidera utilizzare l'account di servizio gestito di gruppo (gMSA) per eseguire i servizi plug-in.


IMPORTANT: Fornire il nome gMSA nel seguente formato: Nome dominio/nome account.


NOTE: GMSA verrà utilizzato come account del servizio di accesso solo per il servizio del plug-in SnapCenter per Windows.

|===
. Fare clic su *Invia*.
+
Se non è stata selezionata la casella di controllo *Salta precheck*, l'host viene validato per verificare se l'host soddisfa i requisiti per l'installazione del plug-in. Lo spazio su disco, la RAM, la versione di PowerShell, la versione di .NET, la posizione (per i plug-in Windows) e la versione di Java (per i plug-in Linux) sono validati in base ai requisiti minimi. Se i requisiti minimi non vengono soddisfatti, vengono visualizzati messaggi di errore o di avviso appropriati.

+
Se l'errore riguarda lo spazio su disco o la RAM, è possibile aggiornare il file web.config che si trova in C: File di programma NetApp SnapCenter WebApp per modificare i valori predefiniti. Se l'errore è correlato ad altri parametri, è necessario risolvere il problema.

+

NOTE: In una configurazione ha, se si aggiorna il file web.config, è necessario aggiornare il file su entrambi i nodi.

. Se il tipo di host è Linux, verificare l'impronta digitale, quindi fare clic su *Confirm and Submit* (Conferma e invia).
+

NOTE: La verifica dell'impronta digitale è obbligatoria anche se lo stesso host è stato aggiunto in precedenza a SnapCenter e l'impronta digitale è stata confermata.

. Monitorare l'avanzamento dell'installazione.
+
I file di log specifici dell'installazione si trovano in /custom_location/snapcenter/logs.


