---
permalink: protect-scc/task_install_snapcenter_plug_in_packages_for_linux_or_windows_on_multiple_remote_hosts_using_cmdlets_scc.html 
sidebar: sidebar 
keywords: credentials 
summary: È possibile installare i pacchetti plug-in SnapCenter per Linux o Windows su più host contemporaneamente utilizzando il cmdlet Install-SmHostPackage PowerShell. 
---
= Installare i pacchetti plug-in SnapCenter per Linux o Windows su più host remoti utilizzando i cmdlet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare i pacchetti plug-in SnapCenter per Linux o Windows su più host contemporaneamente utilizzando il cmdlet Install-SmHostPackage PowerShell.

*Cosa ti serve*

L'utente che aggiunge un host deve disporre dei diritti amministrativi sull'host.

*Fasi*

. Avviare PowerShell.
. Sull'host del server SnapCenter, stabilire una sessione utilizzando il cmdlet Open-SmConnection, quindi immettere le credenziali.
. Installare il plug-in su più host utilizzando il cmdlet Install-SmHostPackage e i parametri richiesti.
+
Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].

+
È possibile utilizzare l'opzione -skipprecheck quando i plug-in sono stati installati manualmente e non si desidera verificare se l'host soddisfa i requisiti per l'installazione del plug-in.

. Inserire le credenziali per l'installazione remota.

