---
sidebar: sidebar 
permalink: sc-automation/task_get_started_with_the_rest_api.html 
keywords:  
summary: 'L"accesso all"API offre una prospettiva prima di iniziare a utilizzarla con i processi di workflow più complessi in un setup live.' 
---
= Inizia con L'API REST
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
È possibile iniziare rapidamente a utilizzare l'API REST di SnapCenter. L'accesso all'API offre una prospettiva prima di iniziare a utilizzarla con i processi di workflow più complessi in un setup live.



== Ciao mondo

È possibile eseguire un semplice comando sul sistema per iniziare a utilizzare l'API REST di SnapCenter e verificarne la disponibilità.

*Cosa ti serve*

* Assicurarsi che l'utility Curl sia disponibile sul sistema.
* Indirizzo IP o nome host del server SnapCenter
* Nome utente e password di un account autorizzato ad accedere all'API REST di SnapCenter.



NOTE: Se le credenziali includono caratteri speciali, è necessario formattarle in modo accettabile per Curl in base alla shell in uso. Ad esempio, è possibile inserire una barra rovesciata prima di ogni carattere speciale o racchiudere l'intero `username:password` stringa tra virgolette singole.

*Passo*

Nell'interfaccia della riga di comando, eseguire quanto segue per recuperare le informazioni del plug-in:

`curl -X GET -u username:password -k "https://<ip_address>/api/hosts?fields=IncludePluginInfo"`

Esempio:

`curl -X GET -u admin:password -k "'https://10.225.87.97/api/hosts?fields=IncludePluginInfo"`
