= 
:allow-uri-read: 


È possibile utilizzare la convenzione di naming predefinita di Snapshot o una convenzione di naming personalizzata. La convenzione di denominazione predefinita dei backup aggiunge un indicatore data e ora ai nomi Snapshot che consente di identificare quando le copie sono state create.

L'istantanea utilizza la seguente convenzione di denominazione predefinita:

`resourcegroupname_hostname_timestamp`

È necessario assegnare un nome logico ai gruppi di risorse di backup, come nell'esempio seguente:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
In questo esempio, gli elementi di sintassi hanno i seguenti significati:

* _dts1_ è il nome del gruppo di risorse.
* _mach1x88_ è il nome host.
* _03-12-2015_23.17.26_ indica data e ora.


In alternativa, è possibile specificare il formato del nome dell'istantanea mentre si proteggono le risorse o i gruppi di risorse selezionando *Usa il formato del nome personalizzato per la copia dell'istantanea*. Ad esempio, customtext_resourcegroup_policy_hostname o resourcegroup_hostname. Per impostazione predefinita, il suffisso dell'indicatore data e ora viene aggiunto al nome dell'istantanea.
