---
permalink: protect-azure/backup-oracle-resource-groups.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Oracle Database, back up, resource groups 
summary: 'Un gruppo di risorse è un insieme di risorse su un host. Un"operazione di backup sul gruppo di risorse viene eseguita su tutte le risorse definite nel gruppo di risorse.' 
---
= Eseguire il backup dei gruppi di risorse Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il backup dei gruppi di risorse composti da più risorse. Un'operazione di backup sul gruppo di risorse viene eseguita su tutte le risorse definite nel gruppo di risorse.

.Fasi
. Nel riquadro di spostamento di sinistra, selezionare *risorse*, quindi selezionare il plug-in appropriato dall'elenco.
. Nella pagina Resources (risorse), selezionare *Resource Group* (Gruppo di risorse) dall'elenco *View* (Visualizza).
. Nella pagina gruppi di risorse, selezionare il gruppo di risorse di cui si desidera eseguire il backup, quindi selezionare *Esegui backup ora*.
. Nella pagina Backup, attenersi alla seguente procedura:
+
.. Se al gruppo di risorse sono associati più criteri, nell'elenco a discesa *criterio* selezionare il criterio che si desidera utilizzare per il backup.
.. Selezionare *Backup*.


. Monitorare l'avanzamento dell'operazione selezionando *Monitor* > *Jobs*.

