---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: 'Creare la credenziale Azure in SnapCenter per accedere all"account Azure NetApp.' 
---
= Creare la credenziale Azure in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare la credenziale Azure in SnapCenter per accedere all'account Azure NetApp.

Prima di creare la credenziale Azure, assicurarsi di aver creato l'entità del servizio in Azure. L'ID tenant, l'ID client e la chiave segreta associati all'identità del servizio saranno necessari per creare la credenziale Azure.

.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *credenziale*.
. Fare clic su *nuovo*.
. Nella pagina credenziali, specificare le seguenti informazioni necessarie per creare la credenziale.
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Nome credenziale
 a| 
Immettere un nome per la credenziale.



 a| 
Modalità di autenticazione
 a| 
Selezionare *Azure Credential* dall'elenco a discesa.



 a| 
ID tenant
 a| 
Immettere l'ID tenant.



 a| 
ID client
 a| 
Immettere l'ID client.



 a| 
Chiave segreta client
 a| 
Immettere la chiave segreta client.

|===
. Fare clic su *OK*.

