---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: 'Creare la credenziale Azure in SnapCenter per accedere all"account Azure NetApp.' 
---
= Creare la credenziale Azure in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare la credenziale Azure in SnapCenter per accedere all'account Azure NetApp.

.Prima di iniziare
* Assicurarsi di aver creato l'entità del servizio in Azure.
* Verificare che l'ID tenant, l'ID client e la chiave segreta associati all'entità del servizio siano disponibili.
+
** L'ID tenant si trova nel portale di Azure nella pagina Panoramica di Entra ID.
** L'ID cliente è anche noto come ID applicazione per l'app aziendale/responsabile del servizio. Questa funzione si trova nel portale Azure nella pagina Panoramica dell'applicazione aziendale creata per fungere da Service Principal per SnapCenter.
** La chiave segreta del client è anche nota come valore segreto. È possibile creare questo segreto client nel portale di Azure accedendo a *registrazioni app* in Entra ID. Dopo aver selezionato l'applicazione aziendale creata, accedere a *certificati e segreti* e quindi *nuovo segreto client*.
+

NOTE: È possibile accedere al valore segreto solo quando viene creato. Non è possibile accedervi in un secondo momento.

** È necessario concedere autorizzazioni al responsabile del servizio. Il ruolo di Contributor consentirà all'entità del servizio di eseguire le azioni richieste in Azure. Per eseguire questa operazione, accedere alla pagina Access Control (IAM) all'interno della pagina Subscription (abbonamento).




.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *credenziale*.
. Fare clic su *nuovo*.
. Nella pagina credenziali, specificare le seguenti informazioni necessarie per creare la credenziale.
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Nome credenziale
 a| 
Immettere un nome per la credenziale.



 a| 
Modalità di autenticazione
 a| 
Selezionare *Azure Credential* dall'elenco a discesa.



 a| 
ID tenant
 a| 
Immettere l'ID tenant.



 a| 
ID client
 a| 
Immettere l'ID client.



 a| 
Chiave segreta client
 a| 
Immettere la chiave segreta client.

|===
. Fare clic su *OK*.

