---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: 'Creare la credenziale per aggiungere l"host del plug-in.' 
---
= Creare la credenziale per aggiungere l'host del plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter.

È necessario creare credenziali per l'installazione dei plug-in di SnapCenter e credenziali aggiuntive per l'esecuzione delle operazioni di protezione dei dati.

.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *credenziale*.
. Fare clic su *nuovo*.
. Nella pagina credenziali, specificare le seguenti informazioni necessarie per creare la credenziale.
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Nome credenziale
 a| 
Immettere un nome per la credenziale.



 a| 
Modalità di autenticazione
 a| 
Selezionare la modalità di autenticazione dall'elenco a discesa.



 a| 
Tipo di autenticazione
 a| 
Selezionare *basato su password* o *basato su chiave SSH* (solo per host Linux).



 a| 
Nome utente
 a| 
Specificare il nome utente.



 a| 
Password
 a| 
Se è stata selezionata l'autenticazione basata su password, specificare la password.



 a| 
Chiave privata SSH
 a| 
Se è stata selezionata l'autenticazione basata su chiave SSH, specificare la chiave privata.



 a| 
Utilizzare i privilegi sudo
 a| 
Selezionare la casella di controllo Usa privilegi sudo se si stanno creando credenziali per un utente non root.


NOTE: Applicabile solo agli utenti Linux.

|===
. Fare clic su *OK*.

