---
permalink: admin/concept_manage_ems_data_collection.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile pianificare e gestire la raccolta di dati EMS (Event Management System) utilizzando i cmdlet PowerShell. La raccolta di dati EMS comprende la raccolta di dettagli sul server SnapCenter, sui pacchetti plug-in SnapCenter installati, sugli host e informazioni simili, quindi l"invio a una macchina virtuale di storage ONTAP specificata.' 
---
= Gestire la raccolta di dati EMS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile pianificare e gestire la raccolta di dati EMS (Event Management System) utilizzando i cmdlet PowerShell. La raccolta di dati EMS comprende la raccolta di dettagli sul server SnapCenter, sui pacchetti plug-in SnapCenter installati, sugli host e informazioni simili, quindi l'invio a una specifica macchina virtuale di storage ONTAP (SVM).


NOTE: L'utilizzo della CPU del sistema è elevato quando è in corso l'attività di raccolta dei dati. L'utilizzo della CPU rimane elevato fino a quando l'operazione è in corso indipendentemente dalle dimensioni dei dati.



== Interrompere la raccolta dei dati EMS

Per impostazione predefinita, la raccolta dei dati EMS viene attivata e viene eseguita ogni sette giorni dopo la data di installazione. È possibile disattivare la raccolta dati in qualsiasi momento utilizzando il cmdlet PowerShell _Disable-SmDataCollectionEMS_.

*Fasi*

. Da una riga di comando PowerShell, stabilire una sessione con SnapCenter immettendo _Open-SmConnection_.
. Disattivare la raccolta dati EMS immettendo _Disable-SmDataCollectionEms_.




== Avviare la raccolta dati EMS

La raccolta dei dati EMS è attivata per impostazione predefinita ed è pianificata per l'esecuzione ogni sette giorni dalla data di installazione. Se è stata disattivata, è possibile avviare nuovamente la raccolta dati EMS utilizzando il cmdlet _Enable-SmDataCollectionEMS_.

L'autorizzazione generate-autosupport-log dell'evento Data ONTAP è stata concessa all'utente della macchina virtuale di storage (SVM).

*Fasi*

. Da una riga di comando PowerShell, stabilire una sessione con SnapCenter immettendo _Open-SmConnection_.
. Abilitare la raccolta dati EMS immettendo _Enable-SmDataCollectionEMS_.




== Modificare il programma di raccolta dei dati EMS e la SVM di destinazione

È possibile utilizzare i cmdlet PowerShell per modificare la pianificazione della raccolta dati EMS o la SVM (Storage Virtual Machine) di destinazione.

*Fasi*

. Dalla riga di comando di PowerShell, per stabilire una sessione con SnapCenter, immettere il cmdlet _Open-SmConnection_.
. Per modificare la destinazione della raccolta dati EMS, immettere il cmdlet _set-SmDataCollectionEmsTarget_.
. Per modificare la pianificazione della raccolta dati EMS, immettere il cmdlet _set-SmDataCollectionEmsSchedule_.




== Monitorare lo stato di raccolta dei dati EMS

È possibile monitorare lo stato della raccolta dati EMS utilizzando diversi cmdlet PowerShell. È possibile ottenere informazioni su pianificazione, destinazione della macchina virtuale di storage (SVM) e stato.

*Fasi*

. Da una riga di comando PowerShell, stabilire una sessione con SnapCenter immettendo _Open-SmConnection_.
. Recuperare le informazioni sulla pianificazione della raccolta dati EMS immettendo _Get-SmDataCollectionEmsSchedule_.
. Recuperare le informazioni sullo stato della raccolta dati EMS immettendo _Get-SmDataCollectionEmsStatus_.
. Recuperare le informazioni sulla destinazione di raccolta dati EMS immettendo _Get-SmDataCollectionEmsTarget_.


*Ulteriori informazioni*

Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guida di riferimento al cmdlet del software SnapCenter"^].
