---
permalink: protect-postgresql/how-resources-resource-groups-and-policies-are-used-for-protecting-postgresql.html 
sidebar: sidebar 
keywords: postgresql 
summary: Prima di utilizzare SnapCenter, è utile comprendere i concetti di base relativi alle operazioni di backup, clonazione e ripristino che si desidera eseguire. Interagisci con risorse, gruppi di risorse e policy per diverse operazioni. 
---
= Modalità di utilizzo di risorse, gruppi di risorse e criteri per la protezione di PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare SnapCenter, è utile comprendere i concetti di base relativi alle operazioni di backup, clonazione e ripristino che si desidera eseguire. Interagisci con risorse, gruppi di risorse e policy per diverse operazioni.

* In genere, le risorse sono cluster PostgreSQL di cui si esegue il backup o la clonazione con SnapCenter.
* Un gruppo di risorse SnapCenter è un insieme di risorse su un host.
+
Quando si esegue un'operazione su un gruppo di risorse, tale operazione viene eseguita sulle risorse definite nel gruppo di risorse in base alla pianificazione specificata per il gruppo di risorse.

+
È possibile eseguire il backup su richiesta di una singola risorsa o di un gruppo di risorse. È inoltre possibile eseguire backup pianificati per singole risorse e gruppi di risorse.

* I criteri specificano la frequenza di backup, la replica, gli script e altre caratteristiche delle operazioni di protezione dei dati.
+
Quando si crea un gruppo di risorse, si selezionano uno o più criteri per tale gruppo. È inoltre possibile selezionare un criterio quando si esegue un backup su richiesta per una singola risorsa.



Un gruppo di risorse definisce ciò che si desidera proteggere e quando si desidera proteggerlo in termini di giorno e ora. Pensa a una policy come a come vuoi proteggerla. Se si esegue il backup di tutti i cluster, ad esempio, è possibile creare un gruppo di risorse che includa tutti i cluster nell'host. È quindi possibile associare due criteri al gruppo di risorse: Una policy giornaliera e una policy oraria. Quando si crea il gruppo di risorse e si allegano i criteri, è possibile configurare il gruppo di risorse in modo che esegua un backup completo ogni giorno.
