---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: 'Le credenziali utilizzano metodi di autenticazione diversi a seconda dell"applicazione o dell"ambiente. Le credenziali autenticano gli utenti in modo che possano eseguire operazioni SnapCenter. È necessario creare un set di credenziali per l"installazione dei plug-in e un altro set per le operazioni di protezione dei dati.' 
---
= Metodi di autenticazione per le credenziali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le credenziali utilizzano metodi di autenticazione diversi a seconda dell'applicazione o dell'ambiente. Le credenziali autenticano gli utenti in modo che possano eseguire operazioni SnapCenter. È necessario creare un set di credenziali per l'installazione dei plug-in e un altro set per le operazioni di protezione dei dati.



== Autenticazione di Windows

Il metodo di autenticazione di Windows esegue l'autenticazione con Active Directory. Per l'autenticazione di Windows, Active Directory viene configurato al di fuori di SnapCenter. SnapCenter esegue l'autenticazione senza alcuna configurazione aggiuntiva. È necessaria una credenziale Windows per eseguire attività come l'aggiunta di host, l'installazione di pacchetti plug-in e la pianificazione dei processi.



== Autenticazione di dominio non attendibile

SnapCenter consente la creazione di credenziali Windows utilizzando utenti e gruppi appartenenti a domini non attendibili. Affinché l'autenticazione abbia esito positivo, è necessario registrare i domini non attendibili con SnapCenter.



== Autenticazione del gruppo di lavoro locale

SnapCenter consente la creazione di credenziali Windows con utenti e gruppi di lavoro locali. L'autenticazione di Windows per gli utenti e i gruppi di lavoro locali non avviene al momento della creazione delle credenziali di Windows, ma viene posticipata fino a quando non vengono eseguite la registrazione dell'host e altre operazioni dell'host.



== Autenticazione di SQL Server

Il metodo di autenticazione SQL esegue l'autenticazione con un'istanza di SQL Server. Ciò significa che un'istanza di SQL Server deve essere rilevata in SnapCenter. Pertanto, prima di aggiungere una credenziale SQL, è necessario aggiungere un host, installare pacchetti plug-in e aggiornare le risorse. È necessaria l'autenticazione di SQL Server per eseguire operazioni come la pianificazione su SQL Server o il rilevamento delle risorse.



== Autenticazione Linux

Il metodo di autenticazione Linux esegue l'autenticazione su un host Linux. L'autenticazione Linux è necessaria durante la fase iniziale di aggiunta dell'host Linux e installazione del pacchetto di plug-in SnapCenter per Linux in remoto dall'interfaccia grafica di SnapCenter.



== Autenticazione AIX

Il metodo di autenticazione AIX esegue l'autenticazione su un host AIX. È necessaria l'autenticazione AIX durante la fase iniziale di aggiunta dell'host AIX e installazione del pacchetto di plug-in SnapCenter per AIX in remoto dalla GUI di SnapCenter.



== Autenticazione del database Oracle

Il metodo di autenticazione del database Oracle esegue l'autenticazione su un database Oracle. Se l'autenticazione del sistema operativo (OS) è disattivata sull'host del database, è necessaria un'autenticazione del database Oracle per eseguire operazioni sul database Oracle. Pertanto, prima di aggiungere una credenziale di database Oracle, è necessario creare un utente Oracle nel database Oracle con privilegi sysdba.



== Autenticazione Oracle ASM

Il metodo di autenticazione Oracle ASM esegue l'autenticazione con un'istanza di Oracle Automatic Storage Management (ASM). Se viene richiesto di accedere all'istanza di Oracle ASM e se l'autenticazione del sistema operativo (OS) è disattivata sull'host del database, è necessaria un'autenticazione Oracle ASM. Pertanto, prima di aggiungere una credenziale Oracle ASM, è necessario creare un utente Oracle con privilegi sysasm nell'istanza di ASM.



== Autenticazione del catalogo RMAN

Il metodo di autenticazione del catalogo RMAN viene autenticato nel database del catalogo Oracle Recovery Manager (RMAN). Se è stato configurato un meccanismo di catalogo esterno e il database è stato registrato nel database del catalogo, è necessario aggiungere l'autenticazione del catalogo RMAN.
