---
permalink: install/configure_two_way_ssl_linux.html 
sidebar: sidebar 
keywords: security,two-way ssl,configure two-way ssl, linux host 
summary: È necessario configurare la comunicazione SSL bidirezionale per proteggere la comunicazione reciproca tra il server SnapCenter su host Linux e i plug-in. 
---
= Configurare la comunicazione SSL bidirezionale sull'host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare la comunicazione SSL bidirezionale per proteggere la comunicazione reciproca tra il server SnapCenter su host Linux e i plug-in.

.Prima di iniziare
* Il certificato CA dovrebbe essere stato configurato per l'host Linux.
* È necessario attivare la comunicazione SSL bidirezionale su tutti gli host plug-in e sul server SnapCenter.


.Fasi
. Copiare *certificate.pem* in _/etc/pki/ca-trust/source/anchors/_.
. Aggiungere i certificati nell'elenco di attendibilità dell'host Linux.
+
** `cp root-ca.pem /etc/pki/ca-trust/source/anchors/`
** `cp certificate.pem /etc/pki/ca-trust/source/anchors/`
** `update-ca-trust extract`


. Verificare se i certificati sono stati aggiunti all'elenco dei certificati attendibili.
`trust list | grep "<CN of your certificate>"`
. Aggiornare *ssl_certificate* e *ssl_certificate_key* nel file SnapCenter *nginx* e riavviare.
+
** `vim /etc/nginx/conf.d/snapcenter.conf`
** `systemctl restart nginx`


. Aggiornare il collegamento della GUI del server SnapCenter.
. Aggiornare i valori delle seguenti chiavi in *SnapManager.Web.UI.dll.config* situato in _ /<installation path>/NetApp/snapcenter/SnapManagerWeb_ e *SMCoreServiceHost.dll.config* situato in _/<installation path>/NetApp/snapcenter/SMCore_.
+
** <add key="SERVICE_CERTIFICATE_PATH" value="<path of certificate.pfx>" />
** <add key="SERVICE_CERTIFICATE_PASSWORD" value="<password>"/>


. Riavviare i seguenti servizi.
+
** `systemctl restart smcore.service`
** `systemctl restart snapmanagerweb.service`


. Verificare che il certificato sia collegato alla porta Web SnapManager.
`openssl s_client -connect localhost:8146 -brief`
. Verificare che il certificato sia collegato alla porta smcore.
`openssl s_client -connect localhost:8145 -brief`
. Gestisci password per archivio chiavi e alias SPL.
+
.. Recuperare la password predefinita del keystore SPL assegnata alla chiave *SPL_KEYSTORE_PASS* nel file di proprietà SPL.
.. Modificare la password dell'archivio chiavi.
`keytool -storepasswd -keystore keystore.jks`
.. Modificare la password per tutti gli alias delle voci di chiave privata.
`keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
.. Aggiorna la stessa password per la chiave *SPL_KEYSTORE_PASS* in _spl.properties_.
.. Riavviare il servizio.


. Sul plug-in host Linux, aggiungere i certificati root e intermedi nel keystore del plug-in SPL.
+
** `keytool -import -trustcacerts -alias <any preferred alias name> -file <path of root-ca.pem> -keystore <path of keystore.jks mentioned in spl.properties file>`
** `keytool -importkeystore -srckeystore <path of certificate.pfx> -srcstoretype pkcs12 -destkeystore <path of keystore.jks mentioned in spl.properties file> -deststoretype JKS`
+
... Controllare le voci in keystore.jks.
`keytool -list -v -keystore <path to keystore.jks>`
... Se necessario, rinominare qualsiasi alias.
`keytool -changealias -alias "old-alias" -destalias "new-alias" -keypass keypass -keystore </path/to/keystore> -storepass storepas`




. Aggiornare il valore di *SPL_CERTIFICATE_ALIAS* nel file _spl.properties_ con l'alias di *certificate.pfx* memorizzato in _keystore.jks_ e riavviare il servizio SPL: `systemctl restart spl`
. Verificare che il certificato sia collegato alla porta smcore.
`openssl s_client -connect localhost:8145 -brief`

