---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: 'SnapCenter 6,1 supporta i sistemi ASA R2 che creano un"esperienza semplificata specifica delle esigenze dei clienti che utilizzano solo SAN.' 
---
= Scopri di più sul supporto dei sistemi ASA R2 in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6,1 supporta i sistemi ASA R2 che creano un'esperienza semplificata specifica delle esigenze dei clienti che utilizzano solo SAN.

I sistemi ASA R2 supportano tutti i protocolli SAN (iSCSI, FC e NVMe su TCP/IP) in una singola implementazione ha-Pair. I protocolli SCSI (iSCSI ed FC) utilizzano un'architettura Active-Active simmetrica per il multipathing, in modo che tutti i percorsi tra gli host e lo storage siano attivi/ottimizzati. I protocolli iSCSI e NVMe/TCP supportano percorsi diretti tra gli host e lo storage.


NOTE: SnapCenter supporta solo VMware Virtual Machine file System (VMFS) sui sistemi ASA R2.

I sistemi ASA R2 introducono l'utilizzo di unità di storage con gruppi di coerenza:

* Un'unità di storage rende disponibile lo spazio di storage per gli host SAN per le operazioni sui dati. Un'unità di storage si riferisce a un LUN per gli host SCSI o a un namespace NVMe per gli host NVMe.
* Un gruppo di coerenza è un insieme di unità di archiviazione gestite come una singola unità.


I sistemi ASA R2 utilizzano le unità di storage e i gruppi di coerenza per semplificare la gestione dello storage e la protezione dei dati. Ad esempio, si supponga di disporre di un database composto da 10 unità di archiviazione in un gruppo di coerenza ed è necessario eseguire il backup dell'intero database. Invece di eseguire il backup di ciascuna unità di archiviazione singolarmente, è possibile proteggere l'intero database eseguendo il backup del gruppo di coerenza.

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Scopri di più sui sistemi ASA R2"].



== Cosa è supportato in SnapCenter 6,1 per sistemi ASA R2

SnapCenter ti consente di eseguire le seguenti operazioni su tutte le applicazioni che sono supportate da SnapCenter se stai utilizzando sistemi storage ASA R2:

* Creazione di backup primari delle applicazioni su VMDK
* Trasferimento delle snapshot del gruppo di coerenza al sistema di storage secondario
* Ripristino dei backup e ripristino da una posizione alternativa
+
** Ripristino in-place da storage primario e secondario utilizzando VMware vMotion
** Connessione e ripristino delle copie da storage primario e secondario


* Clonazione dei backup e clonazione in una posizione alternativa




== Cosa non è supportato in SnapCenter 6,1 per sistemi ASA R2

* RDM (Raw Device Mapping)
* Volumi di applicazioni per Oracle
* SAP HANA NDV
* LockVault
* Snapshot a prova di manomissione
* Gruppo Flex
* Gruppo di coerenza gerarchica
* Migrazione da sistemi ONTAP 9.x a sistemi ASA R2
* Ridenominazione degli snapshot
* Il provisioning secondario della directory log dell'host plug-in SQL non è supportato da SnapCenter. La configurazione deve essere eseguita manualmente utilizzando l'interfaccia CLI di ONTAP o System Manager.

