---
permalink: install/reference_features_enabled_on_your_windows_host_during_installation.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: 'Il programma di installazione del server SnapCenter abilita le funzionalità e i ruoli di Windows sull"host durante l"installazione. Questi potrebbero essere di interesse per la risoluzione dei problemi e la manutenzione del sistema host.' 
---
= Funzionalità abilitate sull'host Windows durante l'installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il programma di installazione del server SnapCenter abilita le funzionalità e i ruoli di Windows sull'host durante l'installazione. Questi potrebbero essere di interesse per la risoluzione dei problemi e la manutenzione del sistema host.

|===
| Categoria | Funzione 


 a| 
Server Web
 a| 
* Internet Information Services
* World Wide Web Services
* Funzionalità HTTP comuni
+
** Documento predefinito
** Navigazione nelle directory
** Errori HTTP
** Reindirizzamento HTTP
** Contenuto statico
** Pubblicazione WebDAV


* Salute e diagnostica
+
** Registrazione personalizzata
** Registrazione HTTP
** Strumenti di logging
** Richiedi Monitor
** Tracciamento


* Caratteristiche delle performance
+
** Compressione del contenuto statico


* Sicurezza
+
** Sicurezza IP
** Autenticazione di base
** Supporto centralizzato dei certificati SSL
** Autenticazione del mapping dei certificati client
** Autenticazione mapping certificati client IIS
** Limitazioni di dominio e IP
** Filtraggio delle richieste
** Autorizzazione URL
** Autenticazione di Windows


* Funzionalità di sviluppo delle applicazioni
+
** Estendibilità di .NET 4.5
** Inizializzazione dell'applicazione
** ASP.NET Core Hosting Bundle a partire dalla versione 8.0.5 e comprendente tutte le patch .NET 8 successive
** Include lato server
** Protocollo WebSocket


* Strumenti di gestione
+
** Console di gestione IIS






 a| 
Script e strumenti di gestione IIS
 a| 
* Servizio di gestione IIS
* Strumenti di gestione Web




 a| 
+.funzionalità di NET Framework 8.0.5+
 a| 
* NET Framework che inizia con la versione 8.0.5 e include tutte le patch .NET 8 successive
* ASP.NET a partire dalla versione 8.0.5 e includendo tutte le patch .NET 8 successive
* Attivazione HTTP di Windows Communication Foundation (WCF) 45
+
** Attivazione TCP
** Attivazione HTTP




Per informazioni specifiche sulla risoluzione dei problemi di .NET, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["L'aggiornamento o l'installazione di SnapCenter non riesce per i sistemi legacy che non dispongono di connettività Internet"^].



 a| 
Accodamento messaggi
 a| 
* Servizi di Accodamento messaggi
+

NOTE: Assicurarsi che nessun'altra applicazione utilizzi il servizio MSMQ creato e gestito da SnapCenter.

* Rabbitmq




 a| 
Servizio di attivazione del processo di Windows
 a| 
* Modello di processo




 a| 
API di configurazione
 a| 
Tutto

|===