---
permalink: install/reference_space_and_sizing_requirements.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Prima di installare il server SnapCenter, è necessario conoscere i requisiti di spazio e dimensionamento. È inoltre necessario applicare gli aggiornamenti di sicurezza e di sistema disponibili. 
---
= Requisiti di spazio e dimensionamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il server SnapCenter, è necessario conoscere i requisiti di spazio e dimensionamento. È inoltre necessario applicare gli aggiornamenti di sicurezza e di sistema disponibili.

|===
| Elemento | Requisiti dell'host Windows | Requisiti degli host Linux 


 a| 
Sistemi operativi
 a| 
Microsoft Windows

Sono supportate solo le versioni in inglese, tedesco, giapponese e cinese semplificato dei sistemi operativi.

Per informazioni aggiornate sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].
 a| 
* Red Hat Enterprise Linux (RHEL) 8 e 9
* SUSE Linux Enterprise Server (SLES) 15


Per informazioni aggiornate sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].



 a| 
Numero minimo di CPU
 a| 
4 core
 a| 
4 core



 a| 
RAM minima
 a| 
8 GB


NOTE: Il pool di buffer di MySQL Server utilizza il 20% della RAM totale.
 a| 
8 GB



 a| 
Spazio minimo su disco rigido per il software e i registri del server SnapCenter
 a| 
7 GB


NOTE: Se il repository SnapCenter si trova nello stesso disco in cui è installato il server SnapCenter, si consiglia di utilizzare 15 GB.
 a| 
15 GB



 a| 
Spazio minimo su disco rigido per il repository SnapCenter
 a| 
8 GB


NOTE: NOTA: Se il server SnapCenter si trova nello stesso disco in cui è installato il repository SnapCenter, si consiglia di utilizzare 15 GB.
 a| 
Non applicabile



 a| 
Pacchetti software richiesti
 a| 
* ASP.NET Core Runtime 8.0.12 (e tutte le successive patch 8,0.x) Hosting Bundle
* PowerShell 7.4.2 o versione successiva


Per informazioni specifiche sulla risoluzione dei problemi di .NET, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["L'aggiornamento o l'installazione di SnapCenter non riesce per i sistemi legacy che non dispongono di connettività Internet"^].
 a| 
* .NET Framework 8.0.12 (e tutte le patch 8,0.x successive)
* PowerShell 7.4.2 o versione successiva
* Nginx è un server web che può essere usato come proxy inverso
* PAM-devel
+
PAM (Plugggable Authentication Modules) è uno strumento di protezione del sistema che consente agli amministratori di sistema di impostare i criteri di autenticazione senza dover ricompilare i programmi che eseguono l'autenticazione.



|===

NOTE: ASP.NET core richiede IIS_IUSRS per accedere al file system temporaneo nel server SnapCenter su Windows.
