---
permalink: install/reference_san_host_requirements.html 
sidebar: sidebar 
keywords: host utilities, Microsoft DSM, Windows MPIO 
summary: 'Se l"host SnapCenter fa parte di un ambiente FC/iSCSI, potrebbe essere necessario installare software aggiuntivo sul sistema per consentire l"accesso allo storage ONTAP.' 
---
= Requisiti degli host SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se l'host SnapCenter fa parte di un ambiente FC/iSCSI, potrebbe essere necessario installare software aggiuntivo sul sistema per consentire l'accesso allo storage ONTAP.

SnapCenter non include le utility host o un DSM. Se l'host SnapCenter fa parte di un ambiente SAN, potrebbe essere necessario installare e configurare il seguente software:

* Utility host
+
Le utility host supportano FC e iSCSI e consentono di utilizzare MPIO sui server Windows. Per ulteriori informazioni, vedere https://["Documentazione delle utility host"^].

* Microsoft DSM per Windows MPIO
+
Questo software funziona con i driver MPIO di Windows per gestire percorsi multipli tra i computer host NetApp e Windows.

+
Per le configurazioni ad alta disponibilità è necessario un DSM.

+

NOTE: Se si utilizza ONTAP DSM, è necessario eseguire la migrazione a Microsoft DSM. Per ulteriori informazioni, vedere https://["Come migrare da ONTAP DSM a Microsoft DSM"^].


