---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: 'Prima di installare il server SnapCenter e i plug-in dell"applicazione o del database, assicurarsi che i requisiti di connessione e porte siano soddisfatti.' 
---
= Requisiti di connessione e porta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il server SnapCenter e i plug-in dell'applicazione o del database, assicurarsi che i requisiti di connessione e porte siano soddisfatti.

* Le applicazioni non possono condividere una porta.
+
Ciascuna porta deve essere dedicata all'applicazione appropriata.

* Per le porte personalizzabili, è possibile selezionare una porta personalizzata durante l'installazione se non si desidera utilizzare la porta predefinita.
+
È possibile modificare una porta del plug-in dopo l'installazione utilizzando la procedura guidata Modify host (Modifica host).

* Per le porte fisse, accettare il numero di porta predefinito.
* Firewall
+
** Firewall, proxy o altri dispositivi di rete non devono interferire con le connessioni.
** Se si specifica una porta personalizzata quando si installa SnapCenter, è necessario aggiungere una regola firewall sull'host del plug-in per tale porta per il caricatore plug-in SnapCenter.




La tabella seguente elenca le diverse porte e i relativi valori predefiniti.

|===
| Port Name (Nome porta) | Numeri di porta | Protocollo | Direzione | Descrizione 


 a| 
Porta SnapCenter
 a| 
8146
 a| 
HTTPS
 a| 
Bidirezionale
 a| 
Questa porta viene utilizzata per la comunicazione tra il client SnapCenter (l'utente SnapCenter) e il server SnapCenter e viene utilizzata anche per la comunicazione dagli host plug-in al server SnapCenter.

È possibile personalizzare il numero di porta.



 a| 
Porta di comunicazione SMCore SnapCenter
 a| 
8145
 a| 
HTTPS
 a| 
Bidirezionale
 a| 
Questa porta viene utilizzata per la comunicazione tra il server SnapCenter e gli host in cui sono installati i plug-in SnapCenter.

È possibile personalizzare il numero di porta.



 a| 
Porta del servizio di pianificazione
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
Questa porta viene utilizzata per orchestrare i flussi di lavoro dello scheduler SnapCenter per tutti i plug-in gestiti all'interno dell'host server SnapCenter in modo centralizzato.

È possibile personalizzare il numero di porta.



 a| 
Porto di RabbitMQ
 a| 
5672
 a| 
TCP
 a| 
 a| 
Questa è la porta predefinita su cui RabbitMQ ascolta e viene utilizzata per la comunicazione tra il servizio Scheduler e SnapCenter sul modello di editore-abbonato.



 a| 
Porta MySQL
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
La porta viene utilizzata per comunicare con il database del repository SnapCenter. È possibile creare connessioni protette dal server SnapCenter al server MySQL. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["Scopri di più"]



 a| 
Host plug-in Windows
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
Questa porta viene utilizzata per la comunicazione tra il server SnapCenter e l'host su cui viene installato il plug-in. Deve essere aperto anche un intervallo di porte dinamiche aggiuntivo specificato da Microsoft.



 a| 
Host plug-in Linux o AIX
 a| 
22
 a| 
SSH
 a| 
Unidirezionale
 a| 
Questa porta viene utilizzata per la comunicazione tra il server SnapCenter e l'host, avviata dal server all'host client.



 a| 
Pacchetto di plug-in SnapCenter per Windows, Linux o AIX
 a| 
8145
 a| 
HTTPS
 a| 
Bidirezionale
 a| 
Questa porta viene utilizzata per la comunicazione tra SMCore e gli host in cui è installato il pacchetto plug-in. Personalizzabile.

È possibile personalizzare il numero di porta.



 a| 
Plug-in SnapCenter per database Oracle
 a| 
27216
 a| 
 a| 
 a| 
La porta JDBC predefinita viene utilizzata dal plug-in per Oracle per la connessione al database Oracle.



 a| 
Plug-in SnapCenter per database Exchange
 a| 
909
 a| 
 a| 
 a| 
NET predefinito. La porta TCP viene utilizzata dal plug-in di Windows per la connessione ai call-back VSS di Exchange.



 a| 
Plug-in supportati da NetApp per SnapCenter
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
Si tratta di una porta interna che viene utilizzata solo sull'host plug-in personalizzato; non è richiesta alcuna eccezione firewall.

La comunicazione tra il server SnapCenter e i plug-in personalizzati viene instradata attraverso la porta 8145.



 a| 
Porta di comunicazione SVM o cluster ONTAP
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
Bidirezionale
 a| 
La porta viene utilizzata da SAL (Storage Abstraction Layer) per la comunicazione tra l'host che esegue il server SnapCenter e SVM. La porta viene attualmente utilizzata anche dagli host plug-in SAL on SnapCenter per Windows per la comunicazione tra l'host plug-in SnapCenter e SVM.



 a| 
Plug-in SnapCenter per database SAP HANA
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
Bidirezionale
 a| 
Per un singolo tenant MDC (Multitenant Database Container), il numero di porta termina con 13; per i non MDC, il numero di porta termina con 15.

È possibile personalizzare il numero di porta.



 a| 
Plug-in SnapCenter per PostgreSQL
 a| 
5432
 a| 
 a| 
 a| 
Questa porta è la porta PostgreSQL predefinita utilizzata per la comunicazione dal plug-in per PostgreSQL al cluster PostgreSQL.

È possibile personalizzare il numero di porta.

|===
Per modificare i dettagli della porta, vedere link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["Modificare gli host dei plug-in"].
