---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: 'È necessario configurare il certificato CA con il sito SnapCenter sull"host Windows.' 
---
= Configurare il certificato CA con il sito SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare il certificato CA con il sito SnapCenter sull'host Windows.

*Fasi*

. Aprire Gestione IIS sul server Windows in cui è installato SnapCenter.
. Nel riquadro di navigazione a sinistra, fare clic su *connessioni*.
. Espandere il nome del server e *Sites*.
. Selezionare il sito Web di SnapCenter su cui si desidera installare il certificato SSL.
. Accedere a *azioni* > *Modifica sito*, fare clic su *associazioni*.
. Nella pagina binding, selezionare *binding for https*.
. Fare clic su *Edit* (Modifica).
. Dall'elenco a discesa SSL certificate (certificato SSL), selezionare il certificato SSL importato di recente.
. Fare clic su *OK*.



NOTE: Se il certificato CA distribuito di recente non è elencato nel menu a discesa, controllare se il certificato CA è associato alla chiave privata.


IMPORTANT: Assicurarsi che il certificato venga aggiunto utilizzando il seguente percorso: *Root console > certificati – computer locale > autorità di certificazione root attendibili > certificati*.
