---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: Prima di aggiungere un host e installare i pacchetti plug-in, è necessario completare tutti i requisiti. 
---
= Prerequisiti per l'aggiunta di host e l'installazione di Plug-in Package per Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiungere un host e installare il pacchetto plug-in per Linux, è necessario completare tutti i requisiti.

* Se si utilizza iSCSI, il servizio iSCSI deve essere in esecuzione.
* È possibile utilizzare l'autenticazione basata su password per l'utente root o non root oppure l'autenticazione basata su chiave SSH.
+

NOTE: La chiave RSA è l'unico formato di chiave SSH supportato per SnapCenter. Consulta l'articolo della Knowledge Base link:https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/How_to_create_an_RSA_key_for_SnapCenter_SSH_Key_Based_credential["Come creare una chiave RSA per le credenziali SSH basate su chiave di SnapCenter"^] per i dettagli su come creare la chiave SSH.

+
Il plug-in SnapCenter per file system Unix può essere installato da un utente non root. Tuttavia, è necessario configurare i privilegi sudo per l'utente non root per installare e avviare il processo di plug-in. Dopo aver installato il plug-in, i processi verranno eseguiti come utenti non root.

* Creare credenziali con la modalità di autenticazione come Linux per l'utente di installazione.
* Devi aver installato Java 17 per SnapCenter 6.2.1 e versioni successive oppure Java 11 per SnapCenter 6.2 e versioni precedenti sul tuo host Linux.
+

NOTE: Assicurati di aver installato solo la versione certificata di Java 17 per SnapCenter 6.2.1 e successive o Java 11 per SnapCenter 6.2 e precedenti sul sistema host Linux.

+
Per informazioni sui download di Java, fare riferimento a link:https://www.oracle.com/java/technologies/downloads/#java17["Scarica Java per tutti i sistemi operativi"^].

* Si dovrebbe avere *bash* come shell predefinita per l'installazione del plug-in.




== Requisiti degli host Linux

Assicurarsi che l'host soddisfi i requisiti prima di installare il pacchetto di plug-in SnapCenter per Linux.

|===
| Elemento | Requisiti 


 a| 
Sistemi operativi
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
2 GB



 a| 
Spazio minimo di installazione e registrazione per il plug-in SnapCenter sull'host
 a| 
2 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di storage da parte della cartella dei log. Lo spazio di log richiesto varia in base al numero delle entità da proteggere e alla frequenza delle operazioni di protezione dei dati. Se lo spazio su disco non è sufficiente, i registri non verranno creati per le operazioni eseguite di recente.



 a| 
Pacchetti software richiesti
 a| 
* Java 17 (Oracle Java, OpenJDK o SAP JDK) per SnapCenter 6.2.1 e versioni successive oppure Java 11 per SnapCenter 6.2 e versioni precedenti



NOTE: Assicurati di aver installato solo la versione certificata di Java 17 per SnapCenter 6.2.1 e successive o Java 11 per SnapCenter 6.2 e precedenti sul sistema host Linux.

Se hai aggiornato Java all'ultima versione, devi assicurarti che l'opzione JAVA_HOME situata in /var/opt/snapcenter/spl/etc/spl.properties sia impostata sulla versione di Java corretta e sul percorso corretto.

|===
Per le informazioni più recenti sulle versioni supportate, consultare la  https://imt.netapp.com/imt/imt.jsp?components=180320;180338;&solution=1257&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].
