---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: Creare un criterio di backup per i file system Unix di cui si desidera eseguire il backup. 
---
= Creare criteri di backup per i file system Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare SnapCenter per eseguire il backup dei file system Unix, è necessario creare un criterio di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup. Un criterio di backup è un insieme di regole che regolano la gestione, la pianificazione e la conservazione dei backup. È inoltre possibile specificare le impostazioni di replica, script e tipo di backup. La creazione di una policy consente di risparmiare tempo quando si desidera riutilizzare la policy su un'altra risorsa o gruppo di risorse.

.Prima di iniziare
* Devi essere pronto per la protezione dei dati completando attività come l'installazione di SnapCenter, l'aggiunta di host, il rilevamento dei file system e la creazione di connessioni al sistema di storage.
* Se si stanno replicando Snapshot in uno storage secondario mirror o vault, l'amministratore di SnapCenter deve aver assegnato le SVM per i volumi di origine e di destinazione.
* Esaminare i prerequisiti e i limiti specifici della sincronizzazione attiva di SnapMirror. Per informazioni, fare riferimento a https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limiti degli oggetti per la sincronizzazione attiva di SnapMirror"].


.A proposito di questa attività
* SnapLock
+
** Se è selezionata l'opzione "conserva le copie di backup per un numero specifico di giorni", il periodo di conservazione SnapLock deve essere minore o uguale ai giorni di conservazione menzionati.
+
La specifica di un periodo di blocco snapshot impedisce l'eliminazione delle istantanee fino alla scadenza del periodo di conservazione.  Questo potrebbe portare a mantenere un numero di Snapshot maggiore del conteggio specificato nel criterio.

+
Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli Snapshot del vault di SnapLock come parte del ripristino ereditano il tempo di scadenza del vault di SnapLock. L'amministratore dello storage dovrebbe ripulire manualmente i cloni dopo il tempo di scadenza del SnapLock.





.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Selezionare *Unix file Systems* dall'elenco a discesa.
. Fare clic su *nuovo*.
. Nella pagina Name (Nome), inserire il nome del criterio e i relativi dettagli.
. Nella pagina Backup e replica, eseguire le seguenti operazioni:
+
.. Specificare le impostazioni di backup.
.. Specificare la frequenza del programma selezionando *on demand*, *Hourly*, *Daily*, *Weekly* o *Monthly*.
.. Nella sezione Seleziona opzioni di replica secondaria, selezionare una o entrambe le seguenti opzioni di replica secondaria:


+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Aggiornare SnapMirror dopo aver creato una copia Snapshot locale
 a| 
Selezionare questo campo per creare copie mirror dei set di backup su un altro volume (replica SnapMirror).

Questa opzione deve essere abilitata per la sincronizzazione attiva di SnapMirror.



 a| 
Aggiornare SnapVault dopo aver creato una copia Snapshot locale
 a| 
Selezionare questa opzione per eseguire la replica del backup disk-to-disk (backup SnapVault).



 a| 
Numero tentativi di errore
 a| 
Immettere il numero massimo di tentativi di replica consentiti prima dell'interruzione dell'operazione.

|===
. Nella pagina di conservazione, specificare le impostazioni di conservazione per il tipo di backup e il tipo di pianificazione selezionato nella pagina Backup e replica:
+
|===


| Se si desidera... | Quindi... 


 a| 
Mantenere un certo numero di istantanee
 a| 
Selezionare *copie da conservare*, quindi specificare il numero di istantanee che si desidera conservare.

Se il numero di istantanee supera il numero specificato, le istantanee vengono eliminate con le copie meno recenti eliminate per prime.


NOTE: Il valore di mantenimento massimo è 1018. I backup non avranno esito positivo se la conservazione viene impostata su un valore superiore a quello supportato dalla versione di ONTAP sottostante.


IMPORTANT: Se si intende attivare la replica SnapVault, è necessario impostare il numero di conservazione su 2 o superiore. Se si imposta il conteggio della conservazione su 1, l'operazione di conservazione potrebbe non riuscire perché il primo Snapshot è il Snapshot di riferimento per la relazione SnapVault fino a quando una snapshot più recente non viene replicata nella destinazione.



 a| 
Conservare le istantanee per un determinato numero di giorni
 a| 
Selezionare *conserva copie per*, quindi specificare il numero di giorni per i quali si desidera conservare le istantanee prima di eliminarle.



 a| 
Periodo di blocco della copia snapshot
 a| 
Selezionare *Periodo di blocco della copia snapshot* e specificare la durata in giorni, mesi o anni.

Il periodo di conservazione di SnapLock deve essere inferiore a 100 anni.

|===
. Selezionare l'etichetta del criterio.
+

NOTE: È possibile assegnare etichette SnapMirror agli snapshot primari per la replica remota, consentendo agli snapshot primari di trasferire l'operazione di replica degli snapshot da SnapCenter ai sistemi secondari ONTAP .  Questa operazione può essere eseguita senza abilitare l'opzione SnapMirror o SnapVault nella pagina dei criteri.

. Nella pagina script, immettere il percorso e gli argomenti del prespt o del postscript che si desidera eseguire rispettivamente prima o dopo l'operazione di backup.
+

NOTE: Controllare se i comandi sono presenti nell'elenco dei comandi disponibili sull'host plug-in dal percorso _ /opt/NetApp/SnapCenter/scc/etc/allowed_Commands.config_.

+
È inoltre possibile specificare il valore di timeout dello script. Il valore predefinito è 60 secondi.

. Esaminare il riepilogo, quindi fare clic su *fine*.

