---
permalink: protect-scu/task_determine_whether_unix_file_systems_are_available_for_backup.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for UNIX file systems, discovery,file systems, UNIX, Unix file systems 
summary: 'Dopo aver installato il plug-in per i file system Unix, i file system sull"host vengono automaticamente rilevati e visualizzati nella pagina risorse.' 
---
= Individuare i file system UNIX disponibili per il backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver installato il plug-in, tutti i file system su quell'host vengono automaticamente rilevati e visualizzati nella pagina risorse. È possibile aggiungere questi file system ai gruppi di risorse per eseguire operazioni di protezione dei dati.

.Prima di iniziare
* Sono necessarie attività quali l'installazione del server SnapCenter, l'aggiunta di host e la creazione di connessioni al sistema di storage.
* Se i file system risiedono su un disco della macchina virtuale (VMDK) o su una mappatura di dispositivi raw (RDM), è necessario implementare il plug-in SnapCenter per VMware vSphere e registrare il plug-in con SnapCenter.
+
Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html["Implementare il plug-in SnapCenter per VMware vSphere"^].



.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *risorse*, quindi selezionare il plug-in appropriato dall'elenco.
. Nella pagina risorse, selezionare *percorso* dall'elenco Visualizza.
. Fare clic su *Aggiorna risorse*.
+
I file system vengono visualizzati insieme a informazioni quali tipo, nome host, gruppi e criteri di risorse associati e stato.


