---
permalink: protect-db2/back-up-databases-using-powershell-cmdlets-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Il backup di un database include la connessione con il server SnapCenter, l"aggiunta di risorse, l"aggiunta di un criterio, la creazione di un gruppo di risorse di backup e il backup.' 
---
= Eseguire il backup dei database utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il backup di un database include la connessione con il server SnapCenter, l'aggiunta di risorse, l'aggiunta di un criterio, la creazione di un gruppo di risorse di backup e il backup.

.Prima di iniziare
* È necessario aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.
* È necessario aver aggiunto la connessione al sistema di storage e creato una credenziale.


.Fasi
. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
PS C:\> Open-SmConnection
----
+
Viene visualizzato il prompt di nome utente e password.

. Aggiungere risorse manuali utilizzando il cmdlet Add-SmResources.
+
Questo esempio mostra come aggiungere un'istanza di IBM DB2:

+
[listing]
----
PS C:\> Add-SmResource -HostName 10.32.212.13 -PluginCode DB2 -ResourceType Instance -ResourceName db2inst1 -StorageFootPrint (@{"VolumeName"="windb201_data01";"LUNName"="windb201_data01";"StorageSystem"="scsnfssvm"}) -MountPoints "D:\"
----
+
Per il database DB2:

+
[listing]
----
PS C:\> Add-SmResource -HostName 10.32.212.13 -PluginCode DB2 -ResourceType Database -ResourceName SALESDB -StorageFootPrint (@{"VolumeName"="windb201_data01";"LUNName"="windb201_data01";"StorageSystem"="scsnfssvm"}) -MountPoints "D:\" -Instance DB2
----
. Creare un criterio di backup utilizzando il cmdlet Add-SmPolicy.
. Proteggere la risorsa o aggiungere un nuovo gruppo di risorse a SnapCenter utilizzando il cmdlet Add-SmResourceGroup.
. Avviare un nuovo processo di backup utilizzando il cmdlet New-SmBackup.
+
Questo esempio mostra come eseguire il backup di un gruppo di risorse:

+
[listing]
----
C:\PS> New-SMBackup -ResourceGroupName 'ResourceGroup_with_Db2_Resources' -Policy db2_policy1
----
+
In questo esempio viene eseguito il backup di un'istanza DB2:

+
[listing]
----
C:\PS> New-SMBackup -Resources @{"Host"="10.32.212.13";"Uid"="DB2INST1";"PluginName"="DB2"} -Policy db2_policy
----
+
In questo esempio viene eseguito il backup di un database DB2:

+
[listing]
----
C:\PS> New-SMBackup -Resources @{"Host"="10.32.212.13";"Uid"="DB2INST1\WINARCDB";"PluginName"="DB2"} -Policy db2_policy
----
. Monitorare lo stato del processo (in esecuzione, completato o non riuscito) utilizzando il cmdlet Get-smJobSummaryReport.
+
[listing]
----
PS C:\> Get-SmJobSummaryReport -JobId 467

SmJobId            : 467
JobCreatedDateTime :
JobStartDateTime   : 27-Jun-24 01:40:09
JobEndDateTime     : 27-Jun-24 01:41:15
JobDuration        : 00:01:06.7013330
JobName            : Backup of Resource Group 'SCDB201WIN_RAVIR1_OPENLAB_NETAPP_LOCAL_DB2_DB2_WINCIR' with policy 'snapshot-based-db2'
JobDescription     :
Status             : Completed
IsScheduled        : False
JobError           :
JobType            : Backup
PolicyName         : db2_policy
JobResultData      :
----
. Monitorare i dettagli del processo di backup, come ID di backup, nome del backup per eseguire operazioni di ripristino o clonazione, utilizzando il cmdlet Get-SmBackupReport.
+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 467

BackedUpObjects           : {WINCIR}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 84
SmJobId                   : 467
StartDateTime             : 27-Jun-24 01:40:09
EndDateTime               : 27-Jun-24 01:41:15
Duration                  : 00:01:06.7013330
CreatedDateTime           : 27-Jun-24 18:39:45
Status                    : Completed
ProtectionGroupName       : HOSTFQDN_DB2_DB2_WINCIR
SmProtectionGroupId       : 23
PolicyName                : db2_policy
SmPolicyId                : 13
BackupName                : HOSTFQDN _DB2_DB2_WINCIR_HOST_06-27-2024_01.40.09.7397
VerificationStatus        : NotApplicable
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
PluginCode                : SCC
PluginName                : DB2
PluginDisplayName         : IBM DB2
JobTypeId                 :
JobHost                   : HOSTFQDN
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento anche a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento al cmdlet del software SnapCenter"^].
