---
permalink: protect-db2/clone-ibm-db2-backups-using-powershell-cmdlets.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Il flusso di lavoro dei cloni include la pianificazione, l"esecuzione dell"operazione di cloni e il monitoraggio dell"operazione.' 
---
= Clona i backup del database IBM DB2 utilizzando i cmdlet PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il flusso di lavoro dei cloni include la pianificazione, l'esecuzione dell'operazione di cloni e il monitoraggio dell'operazione.

È necessario aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.

Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento anche a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento al cmdlet del software SnapCenter"^].

.Fasi
. Avviare una sessione di connessione con il server SnapCenter per un utente specifico utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
PS C:\> Open-SmConnection
----
. Recuperare i backup per eseguire l'operazione di clonazione utilizzando il cmdlet Get-SmBackup.
+
Questo esempio mostra che sono disponibili due backup per la clonazione:

+
[listing]
----
 C:\PS> Get-SmBackup

        BackupId                      BackupName                    BackupTime                    BackupType
        --------                      ----------                    ----------                    ----------
         1                     Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM          Full Backup
         2                     Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
. Avviare un'operazione di clonazione da un backup esistente e specificare gli indirizzi IP di esportazione NFS su cui esportare i volumi clonati.
+
Questo esempio mostra che il backup da clonare ha un indirizzo IP NFSExportIPs di 10.32.212.14:

+
Per il database DB2:

+
[listing]
----
PS C:\> New-SmClone -Resources @{"Host"="10.32.212.13";"Uid"="db2inst1\BOOKS"} -BackupName 'scdb201_gdl_openlab_netapp_local_DB2_db2inst1_BOOKS_scdb201_05-15-2024_00.29.20.1466' -AppPluginCode DB2 -CloneToInstance '10.32.212.14' -CloneInstance db2inst1 -CloneName BOOKS -NFSExportIPs 10.32.212.14
----
+
Per DB2 esempio:

+
[listing]
----
PS C:\> New-SmClone -Resources @{"Host"="10.32.212.13";"Uid"="DB2"} -BackupName 'scdb201_gdl_openlab_netapp_local_DB2_db2inst1_BOOKS_scdb201_05-15-2024_00.29.20.1466' -AppPluginCode DB2 -CloneToInstance '10.32.212.14' -CloneName Db2 -NFSExportIPs 10.32.212.14
----
+

NOTE: Se NFSExportIP non viene specificato, il valore predefinito viene esportato nell'host di destinazione del clone.

. Verificare che i backup siano stati clonati correttamente utilizzando il cmdlet Get-SmCloneReport per visualizzare i dettagli del processo clone.
+
È possibile visualizzare dettagli quali ID clone, data e ora di inizio, data e ora di fine.

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

    SmCloneId           : 1
    SmJobId             : 186
    StartDateTime       : 8/3/2015 2:43:02 PM
    EndDateTime         : 8/3/2015 2:44:08 PM
    Duration            : 00:01:06.6760000
    Status              : Completed
    ProtectionGroupName : Draper
    SmProtectionGroupId : 4
    PolicyName          : OnDemand_Clone
    SmPolicyId          : 4
    BackupPolicyName    : OnDemand_Full_Log
    SmBackupPolicyId    : 1
    CloneHostName       : SCSPR0054212005.mycompany.com
    CloneHostId         : 4
    CloneName           : Draper__clone__08-03-2015_14.43.53
    SourceResources     : {Don, Betty, Bobby, Sally}
    ClonedResources     : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER, Sally_DRAPER}
    SmJobError          :
----

