---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: Prima di utilizzare SnapCenter per eseguire il backup delle risorse del database IBM DB2, è necessario creare un criterio di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup. Un criterio di backup è un insieme di regole che regolano la gestione, la pianificazione e la conservazione dei backup. 
---
= Creare criteri di backup per IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare SnapCenter per eseguire il backup delle risorse IBM DB2, è necessario creare un criterio di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup. Un criterio di backup è un insieme di regole che regolano la gestione, la pianificazione e la conservazione dei backup.

.Prima di iniziare
* È necessario aver definito la strategia di backup.
+
Per informazioni dettagliate, vedere le informazioni sulla definizione di una strategia di protezione dei dati per i database IBM DB2.

* Devi essere preparato per la protezione dei dati completando attività come l'installazione di SnapCenter, l'aggiunta di host, la configurazione delle connessioni del sistema di storage e l'aggiunta di risorse.
* L'amministratore di SnapCenter deve aver assegnato le SVM per i volumi di origine e destinazione se si sta replicando gli snapshot in un mirror o un vault.
+
Inoltre, è possibile specificare le impostazioni di replica, script e applicazione nel criterio. Queste opzioni consentono di risparmiare tempo quando si desidera riutilizzare il criterio per un altro gruppo di risorse.



.A proposito di questa attività
* SnapLock
+
** Se è selezionata l'opzione "conserva le copie di backup per un numero specifico di giorni", il periodo di conservazione SnapLock deve essere minore o uguale ai giorni di conservazione menzionati.
** La specifica di un periodo di blocco dello snapshot impedisce l'eliminazione degli snapshot fino alla scadenza del periodo di conservazione. Ciò potrebbe portare a mantenere un numero maggiore di snapshot rispetto al conteggio specificato nel criterio.
** Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli snapshot del vault di SnapLock come parte del ripristino ereditano il tempo di scadenza del vault di SnapLock. L'amministratore dello storage dovrebbe ripulire manualmente i cloni dopo il tempo di scadenza del SnapLock.




.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Fare clic su *nuovo*.
. Nella pagina Name (Nome), inserire il nome del criterio e i relativi dettagli.
. Nella pagina tipo di criterio, effettuare le seguenti operazioni:
+
.. Selezionare il tipo di archiviazione.
.. Nella sezione *Impostazioni di backup personalizzate*, specificare le impostazioni di backup specifiche da passare al plug-in in formato key-value.
+
È possibile fornire più valori chiave da passare al plug-in.



. Nella pagina Snapshot and Replication (istantanea e replica), eseguire le seguenti operazioni.
+
.. Specificare la frequenza del programma selezionando *on demand*, *Hourly*, *Daily*, *Weekly* o *Monthly*.
+

NOTE: È possibile specificare la pianificazione (data di inizio, data di fine e frequenza) per l'operazione di backup durante la creazione di un gruppo di risorse. Ciò consente di creare gruppi di risorse che condividono la stessa policy e frequenza di backup, ma consente anche di assegnare diverse pianificazioni di backup a ogni policy.

+

NOTE: Se sono previste le 2:00, la programmazione non verrà attivata durante l'ora legale (DST).

.. Nella sezione Impostazioni istantanea, effettuare le seguenti operazioni:
+
|===
| Se si desidera... | Quindi... 


 a| 
Conservare un certo numero di snapshot
 a| 
Selezionare *copie da conservare*, quindi specificare il numero di istantanee che si desidera conservare.

Se il numero di istantanee supera il numero specificato, le istantanee vengono eliminate con le copie meno recenti eliminate per prime.



 a| 
Conservare le istantanee per un determinato numero di giorni
 a| 
Selezionare *conserva copie per*, quindi specificare il numero di giorni per i quali si desidera conservare le istantanee prima di eliminarle.



 a| 
Periodo di blocco della copia dello snapshot primario
 a| 
Se si desidera specificare il periodo di blocco dello snapshot per il primario, selezionare periodo di blocco della copia Snapshot e selezionare giorni, mesi o anni.

Il periodo di conservazione di SnapLock deve essere inferiore a 100 anni.



 a| 
Periodo di blocco dell'istantanea secondaria
 a| 
Selezionare *periodo blocco copia istantanea secondaria*, quindi giorni, mesi o anni.

|===
+

IMPORTANT: Per i backup basati su copia Snapshot, è necessario impostare il numero di conservazione su 2 o superiore se si intende attivare la replica SnapVault. Se si imposta il conteggio della conservazione su 1, l'operazione di conservazione potrebbe non riuscire perché il primo snapshot è lo snapshot di riferimento per la relazione SnapVault finché non viene replicato nella destinazione uno snapshot più recente.

.. Selezionare un'etichetta Snapshot.
+
A seconda dell'etichetta Snapshot selezionata, ONTAP applica la politica di conservazione Snapshot secondaria corrispondente all'etichetta.

+

NOTE: Se è stato selezionato *Update SnapMirror dopo la creazione di una copia Snapshot locale*, è possibile specificare l'etichetta del criterio secondario. Tuttavia, se è stato selezionato *Aggiorna SnapVault dopo la creazione di una copia Snapshot locale*, è necessario specificare l'etichetta del criterio secondario.



. Nella sezione Seleziona opzioni di replica secondaria, selezionare una o entrambe le seguenti opzioni di replica secondaria:
+

NOTE: È necessario selezionare le opzioni di replica secondarie per *periodo di blocco della copia dello snapshot secondario* per essere efficace.

+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Aggiornare SnapMirror dopo aver creato una copia Snapshot locale
 a| 
Selezionare questo campo per creare copie mirror dei set di backup su un altro volume (replica SnapMirror).

Questa opzione deve essere abilitata per la sincronizzazione attiva di SnapMirror.



 a| 
Aggiornare SnapVault dopo aver creato una copia Snapshot locale
 a| 
Selezionare questa opzione per eseguire la replica del backup disk-to-disk (backup SnapVault).



 a| 
Etichetta del criterio secondario
 a| 
Selezionare un'etichetta Snapshot.

A seconda dell'etichetta Snapshot selezionata, ONTAP applica la politica di conservazione Snapshot secondaria corrispondente all'etichetta.


NOTE: Se è stato selezionato *Update SnapMirror dopo la creazione di una copia Snapshot locale*, è possibile specificare l'etichetta del criterio secondario. Tuttavia, se è stato selezionato *Aggiorna SnapVault dopo la creazione di una copia Snapshot locale*, è necessario specificare l'etichetta del criterio secondario.



 a| 
Numero tentativi di errore
 a| 
Immettere il numero massimo di tentativi di replica consentiti prima dell'interruzione dell'operazione.

|===
+

NOTE: È necessario configurare il criterio di conservazione SnapMirror in ONTAP per lo storage secondario, in modo da evitare di raggiungere il limite massimo di Snapshot sullo storage secondario.

. Esaminare il riepilogo, quindi fare clic su *fine*.

