---
permalink: protect-db2/snapcenter-plug-in-for-ibm-db2-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Il plug-in SnapCenter per IBM DB2 è un componente lato host del software NetApp SnapCenter che consente la gestione della protezione dei dati integrata con l"applicazione dei database IBM DB2. Il plug-in per database IBM DB2 automatizza il backup, il ripristino e la clonazione dei database IBM DB2 nell"ambiente SnapCenter.' 
---
= Panoramica del plug-in SnapCenter per IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per il database IBM DB2 è un componente lato host del software NetApp SnapCenter che consente la gestione della protezione dei dati integrata con l'applicazione dei database IBM DB2. Il plug-in per database IBM DB2 automatizza il backup, il ripristino e la clonazione dei database IBM DB2 nell'ambiente SnapCenter.

* SnapCenter 6,0 supporta IBM DB2 10,5 e versioni successive.
* SnapCenter 6.0.1 supporta IBM DB2 9,7.x e versioni successive. Inoltre, a partire da SnapCenter 6,0.1, è supportato IBM DB2 su AIX.


SnapCenter supporta le configurazioni DB2 a istanza singola e a più istanze. È possibile utilizzare il plug-in per IBM DB2 Database in ambienti Linux e Windows. Negli ambienti Windows, DB2 sarà supportato come risorsa manuale.


NOTE: I sistemi DB2 PureScale e DB2 Multipode (DPF) non sono supportati.

Una volta installato il plug-in per database IBM DB2, è possibile utilizzare SnapCenter con tecnologia NetApp SnapMirror per creare copie mirror dei set di backup su un altro volume. È inoltre possibile utilizzare il plug-in con la tecnologia NetApp SnapVault per eseguire la replica del backup disk-to-disk per garantire la conformità agli standard.

Il plug-in SnapCenter per DB2 supporta NFS e SAN su layout di storage di file ONTAP e Azure NetApp.

VMDK o layout dello storage virtuale non sono supportati.
