---
permalink: protect-db2/storage-types-supported-by-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: storage types, 
summary: 'SnapCenter supporta un"ampia gamma di tipi di storage su macchine fisiche e macchine virtuali (VM). Prima di installare il plug-in SnapCenter per IBM DB2, è necessario verificare il supporto per il tipo di archiviazione in uso.' 
---
= Tipi di storage supportati dal plug-in SnapCenter per IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter supporta un'ampia gamma di tipi di storage su macchine fisiche e macchine virtuali (VM). Prima di installare il plug-in SnapCenter per IBM DB2, è necessario verificare il supporto per il tipo di archiviazione in uso.

|===
| Macchina | Tipo di storage 


 a| 
Server fisico
 a| 
* LUN connessi a FC
* LUN connessi a iSCSI
* Volumi connessi a NFS




 a| 
VMware ESXi
 a| 
* Il completamento delle LUN RDM collegate da un HBASCAN ESXi FC o iSCSI degli HBA (host bus adapter) potrebbe richiedere molto tempo, in quanto SnapCenter esegue la scansione di tutti gli adattatori bus host presenti nell'host.
+
È possibile modificare il file *LinuxConfig.pm* situato in _/opt/NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ per impostare il valore del parametro *SCSI_HOSTS_OPTIMIZED_RESCAN* su 1 per ripetere la scansione solo degli HBA elencati in HBA_DRIVER_NAMES.

* LUN iSCSI collegati direttamente al sistema guest dall'iniziatore iSCSI
* VMDK su datastore NFS
* VMDK in VMFS creato
* Volumi NFS collegati direttamente al sistema guest
* Datastore vVol in NFS e SAN
+
È possibile eseguire il provisioning del datastore vVol solo con i tool ONTAP per VMware vSphere.



|===