---
permalink: protect-nsp/install_the_netapp_supported_plugins_on_linux_hosts_using_the_command_line_interface.html 
sidebar: sidebar 
keywords: install, NetApp supported plug-in 
summary: 'È necessario installare i plug-in supportati da SnapCenter NetApp utilizzando l"interfaccia utente di SnapCenter. Se l"ambiente in uso non consente l"installazione remota del plug-in dall"interfaccia utente di SnapCenter, è possibile installare il plug-in supportato da NetApp in modalità console o in modalità automatica utilizzando l"interfaccia a riga di comando (CLI).' 
---
= Installare i plug-in supportati da NetApp sugli host Linux utilizzando l'interfaccia della riga di comando
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare i plug-in supportati da NetApp utilizzando l'interfaccia utente di SnapCenter. Se l'ambiente in uso non consente l'installazione remota del plug-in dall'interfaccia utente di SnapCenter, è possibile installare i plug-in supportati da NetApp in modalità console o in modalità silent utilizzando l'interfaccia a riga di comando (CLI).

.Fasi
. Copiare il file di installazione del pacchetto di plug-in SnapCenter per Linux (snapcenter_linux_host_plugin.bin) da C:\ProgramData\NetApp\SnapCenter\Package Repository nell'host in cui si desidera installare i plug-in supportati da NetApp.
+
È possibile accedere a questo percorso dall'host in cui è installato il server SnapCenter.

. Dal prompt dei comandi, accedere alla directory in cui è stato copiato il file di installazione.
. Installare il plug-in: `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -DPORT specifica la porta di comunicazione HTTPS SMCore.
** -DSERVER_IP specifica l'indirizzo IP del server SnapCenter.
** -DSERVER_HTTPS_PORT specifica la porta HTTPS del server SnapCenter.
** -DUSER_INSTALL_DIR specifica la directory in cui si desidera installare il pacchetto di plug-in SnapCenter per Linux.
** DINSTALL_LOG_NAME specifica il nome del file di log.


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. Aggiungere l'host al server SnapCenter utilizzando il cmdlet Add-Smhost e i parametri richiesti.
+
Le informazioni relative ai parametri che possono essere utilizzati con il comando e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, fare riferimento anche a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento al cmdlet del software SnapCenter"^].

. Accedere a SnapCenter e caricare il plug-in supportato da NetApp dall'interfaccia utente o utilizzando i cmdlet PowerShell.
+
È possibile caricare il plug-in supportato da NetApp dall'interfaccia utente facendo riferimento alla link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["Aggiungere host e installare pacchetti plug-in su host remoti"] sezione.

+
La guida in linea del cmdlet di SnapCenter e le informazioni di riferimento del cmdlet contengono ulteriori informazioni sui cmdlet di PowerShell.

+
https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento al cmdlet del software SnapCenter"^].


