---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: Prima di aggiungere un host e installare i pacchetti plug-in, è necessario completare tutti i requisiti. I plug-in supportati da NetApp possono essere utilizzati in ambienti Windows e Linux. 
---
= Prerequisiti per l'aggiunta di host e l'installazione dei plug-in supportati da NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiungere un host e installare i pacchetti plug-in, è necessario completare tutti i requisiti. I plug-in supportati da NetApp possono essere utilizzati in ambienti Windows e Linux.

* È necessario aver creato un plug-in personalizzato. Per ulteriori informazioni, consultare le informazioni per gli sviluppatori.
+
link:develop_a_plug_in_for_your_application.html["Sviluppare un plug-in per l'applicazione"]

* È necessario aver installato Java 11 sull'host Linux o Windows.
* Quando si installa un plug-in su un host Windows, se si specifica una credenziale non integrata o se l'utente appartiene a un utente del gruppo di lavoro locale, è necessario disattivare il controllo dell'account utente sull'host.
* I plug-in supportati da NetApp devono essere disponibili sull'host client da cui viene eseguita l'operazione add host.




== Generale

Se si utilizza iSCSI, il servizio iSCSI dovrebbe essere in esecuzione.



== Hash SHA512

* Per i plug-in supportati da NetApp, è necessario assicurarsi di aver aggiunto l'hash SHA512 del file del plug-in supportato da NetApp al file _custom_plugin_checksum_list_.
+
** Per l'host Linux, l'hash SHA512 si trova in _/var/opt/snapcenter/scc/custom_plugin_checksum_list.txt_
** Per gli host Windows, l'hash SHA512 si trova in _C: File di programma NetApp, SnapCenter Plug-in Creator, ecc. custom_plugin_checksum_list.txt_
+
Per il percorso di installazione personalizzato, l'hash SHA512 si trova in _<custom path>/NetApp/SnapCenter/SnapCenter Plug-in Creator/etc/custom_plugin_checksum_list.txt_



+
Il plugin_personalizzato_checksum_list fa parte dell'installazione del plug-in supportato da NetApp sull'host da SnapCenter.

* Per i plug-in supportati da NetApp creati per l'applicazione, è necessario aver eseguito la seguente procedura:
+
.. Ha generato l'hash SHA512 del file zip del plug-in.
+
È possibile utilizzare strumenti online come https://emn178.github.io/online-tools/sha512_file_hash.html["Hash SHA512"^].

.. Aggiunto l'hash SHA512 generato al file custom_plugin_checksum_list in una nuova riga.
+
I commenti iniziano con il simbolo n. per identificare il plug-in a cui appartiene l'hash.

+
Di seguito è riportato un esempio di una voce di hash SHA512 nel file checksum:

+
....
#ORASCPM
03721f567a1e4a1cb5569066b9a58af619ee12b1f8713108f81b696cfbdb81c25232fa63d6e6777a2b2a1ec068bb0a93a59a8ade71587182f8bccbe81f7e0ba6
....






== Host Windows

* È necessario disporre di un utente di dominio con privilegi di amministratore locale con autorizzazioni di accesso locale sull'host remoto.
* Se si gestiscono i nodi del cluster in SnapCenter, è necessario disporre di un utente con privilegi amministrativi per tutti i nodi del cluster.




== Host Linux

* È necessario aver attivato la connessione SSH basata su password per l'utente root o non root.
* È necessario aver installato Java 11 sull'host Linux.
+
Se si utilizza Windows Server 2019 o Windows Server 2016 per l'host SnapCenter Server, è necessario installare Java 11. Lo strumento matrice di interoperabilità (IMT) contiene le informazioni più recenti sui requisiti.

+
http://www.java.com/en/download/manual.jsp["Download Java per tutti i sistemi operativi"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"]

* Per consentire l'accesso a diversi percorsi, è necessario configurare i privilegi sudo per l'utente non root. Aggiungere le seguenti righe al file /etc/sudoers usando l'utility visudo Linux.
+

NOTE: Assicurarsi di utilizzare sudo versione 1.8.7 o successiva.

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ è il nome dell'utente non root creato.

+
È possibile ottenere il _checksum_value_ dal file *sc_unix_plugins_checksum.txt*, che si trova in:

+
** _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ se il server SnapCenter è installato sull'host Windows.
** _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ se il server SnapCenter è installato sull'host Linux.
+

IMPORTANT: L'esempio deve essere utilizzato solo come riferimento per la creazione di dati personali.




