---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: È necessario conoscere il sistema di storage, le applicazioni e i database supportati. 
---
= Applicazioni e sistemi storage supportati da SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dovresti conoscere i sistemi storage, le applicazioni e i database supportati da SnapCenter.



== Sistemi storage supportati

* NetApp ONTAP 9.12.1 e versioni successive
* Azure NetApp Files
* Amazon FSX per NetApp ONTAP
+
Amazon FSx for NetApp ONTAP supporta la memoria non volatile express (NVMe) tramite Transport Control Protocol (TCP).

+
Per informazioni su Amazon FSX per NetApp ONTAP, vedere https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentazione di Amazon FSX per NetApp ONTAP"^].

* Sistemi NetApp ASA r2 che eseguono NetApp ONTAP 9.16.1 e versioni successive
+
Se si utilizzano SnapCenter Server 6.2 e i plug-in SnapCenter 6.2, è necessario utilizzare ONTAP 9.17.1.





== Applicazioni e database supportati

SnapCenter supporta la protezione di diverse applicazioni e database. Per informazioni dettagliate sulle applicazioni e i database supportati, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^].

SnapCenter supporta la protezione dei carichi di lavoro Oracle e Microsoft SQL in ambienti VMware Cloud su Amazon Web Services (AWS) Software-Defined Data Center (SDDC). https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["Scopri di più"^].
