---
permalink: 'release-notes/what"s-new-in-snapcenter61.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.2 
summary: La release 6,1 del software SnapCenter include diverse nuove funzioni e miglioramenti. 
---
= Novità del SnapCenter software 6.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versione 6.2 del SnapCenter software include la seguente nuova funzionalità.

|===
| Aggiornare | Descrizione 


| link:../get-started/reference_supported_storage_systems_and_applications.html["Supporto per i sistemi ASA R2"]  a| 
SnapCenter 6.2 (server e plug-in) insieme a ONTAP 9.17.1 supporta sia la protezione primaria che quella secondaria delle applicazioni in esecuzione su sistemi fisici (Linux e Windows) e Virtual Machine File System (VMFS) utilizzando gruppi di coerenza gerarchica.

Dopo l'aggiornamento a SnapCenter 6.2 e ONTAP 9.17.1, SnapCenter modifica i gruppi di coerenza semplici in gruppi di coerenza gerarchici durante il primo backup pianificato.

|===


== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e dei NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vedere illink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione della console NetApp"^] .
