---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: La versione 6,0 del software SnapCenter include diverse nuove funzioni e miglioramenti. 
---
= Novità del software SnapCenter 6,0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versione 6,0 del software SnapCenter include diverse nuove funzioni e miglioramenti.

|===
| Aggiornare | Descrizione 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["Supporto di plug-in per carichi di lavoro Enterprise con supporto NetApp"]  a| 
SnapCenter fornisce i plug-in per gestire carichi di lavoro come PostgreSQL, MySQL e IBM DB2. Puoi rilevare, eseguire il backup, ripristinare, montare e clonare automaticamente i workload.

SnapCenter fornisce anche i plug-in per gestire workload come SAP ASE, SAP MaxDB, MongoDB, applicazioni Oracle e storage ONTAP. Puoi eseguire backup, ripristino e clonazione dei workload.



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["Supporto della versione Linux di SnapCenter per workload on-premise e cloud"]  a| 
Sono ora disponibili binari SnapCenter separati per versioni di Linux come Red Hat Enterprise Linux (RHEL), Oracle Linux e SUSE Linux Enterprise Server (SLES).

* Supporta Azure NetApp Files, Amazon FSX per lo storage NetApp ONTAP, Cloud Volumes ONTAP e ONTAP.
* File binari separati per le versioni di Linux come Red Hat Enterprise Linux (RHEL), Oracle Linux e SUSE Linux Enterprise Server (SLES).
* Supporta database classici come SAP HANA, Oracle, IBM DB2, SAP ASE, SAP MaxDB.
* Supporta workload moderni come PostgreSQL, MySQL e MongoDB.
* Supporto di plug-in per ONTAP Volumes e file system Linux per la protezione di applicazioni non supportate o sviluppate internamente.




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["Supporto per la sincronizzazione attiva di SnapMirror"]  a| 
Puoi ora utilizzare SnapCenter per configurare le funzionalità di sincronizzazione attiva di SnapMirror ed eseguire in modo efficace il backup, il ripristino e la clonazione di carichi di lavoro SAN per database e macchine virtuali VMware. Ciò garantisce un failover trasparente delle applicazioni e la continuità del business.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["Supporto per Microsoft SQL Server su SMB3"]  a| 
Ora puoi utilizzare SnapCenter per proteggere i database Microsoft SQL Server implementati sul protocollo SMB3 in ONTAP, Azure NetApp Files, Amazon FSX per NetApp ONTAP e Cloud Volumes ONTAP.



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["Supporto per NVMe/TCP"]  a| 
SnapCenter ora supporta il protocollo NVMe over TCP per eseguire il backup e il ripristino di applicazioni e file system.



| Supporto per volumi virtuali VMware vSphere (vVol)  a| 
È ora possibile utilizzare SnapCenter per proteggere i database e i file system distribuiti su vVol.

|===