---
permalink: protect-mysql/configure-CA-certificate-for-mysql-on-windows-host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Configurare il certificato CA per il servizio plug-in MySQL di SnapCenter sull"host Windows' 
---
= Configurare il certificato CA per il servizio plug-in MySQL di SnapCenter sull'host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario gestire la password del keystore dei plug-in e il relativo certificato, configurare il certificato CA, configurare i certificati radice o intermedi per il trust-store dei plug-in e configurare la coppia di chiavi firmata dalla CA per il trust-store dei plug-in con il servizio plug-in SnapCenter per attivare il certificato digitale installato.

Il plug-in utilizza il file _keystore.jks_, che si trova in _C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_ sia come archivio attendibile che come archivio chiavi.



== Gestisci la password per il keystore del plug-in e l'alias della coppia di chiavi firmata dalla CA in uso

.Fasi
. È possibile recuperare la password predefinita del keystore del plug-in dal file delle proprietà dell'agente plug-in.
+
È il valore corrispondente alla chiave _KEYSTORE_PASS_.

. Modificare la password del keystore:
+
_keytool -storepasswd -keystore keystore.jks_

+

NOTE: Se il comando "keytool" non viene riconosciuto dal prompt dei comandi di Windows, sostituire il comando keytool con il relativo percorso completo.

+
_C: File di programma Java <jdk_version> keytool.exe" -storepasswd -keystore keystore.jks_

. Modificare la password per tutti gli alias delle chiavi private nel keystore con la stessa password utilizzata per il keystore:
+
_keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.jks_

+
Aggiornare lo stesso per la chiave KEYSTORE_PASS nel file _agent.properties_.

. Riavviare il servizio dopo aver modificato la password.
+

NOTE: La password per l'archivio chiavi del plug-in e per tutte le password alias associate della chiave privata devono essere le stesse.





== Configurare i certificati radice o intermedi per collegare trust-store

È necessario configurare i certificati radice o intermedi senza la chiave privata per collegare trust-store.

.Fasi
. Passare alla cartella contenente il keystore del plug-in _C:\Programmi\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_
. Individuare il file 'keystore.jks'.
. Elencare i certificati aggiunti nel keystore:
+
_keytool -list -v -keystore keystore.jks_

. Aggiungere un certificato root o intermedio:
+
_Keytool -import -trustcaacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks_

. Riavviare il servizio dopo aver configurato i certificati radice o intermedi per collegare trust-store.



NOTE: Aggiungere il certificato CA principale e i certificati CA intermedi.



== Configurare la coppia di chiavi firmata da CA per collegare l'archivio attendibile

È necessario configurare la coppia di chiavi firmata dalla CA nel trust-store del plug-in.

.Fasi
. Passare alla cartella contenente il keystore del plug-in _C:\Programmi\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc_
. Individuare il file _keystore.jks_.
. Elencare i certificati aggiunti nel keystore:
+
_keytool -list -v -keystore keystore.jks_

. Aggiungere il certificato CA con chiave pubblica e privata.
+
_Keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS_

. Elencare i certificati aggiunti nel keystore.
+
_keytool -list -v -keystore keystore.jks_

. Verificare che il keystore contenga l'alias corrispondente al nuovo certificato CA aggiunto al keystore.
. Modificare la password della chiave privata aggiunta per il certificato CA in password archivio chiavi.
+
La password predefinita del keystore del plug-in è il valore della chiave KEYSTORE_PASS nel file agent.properties.

+
_Keytool -keypasswd -alias "alias_name_in_CA_cert" -keystore keystore.jks_

. Configurare il nome alias del certificato CA nel file _agent.properties_.
+
Aggiornare questo valore con la chiave SCC_CERTIFICATE_ALIAS.

. Riavviare il servizio dopo aver configurato la coppia di chiavi firmate dalla CA per collegare trust-store.




== Configurare l'elenco di revoche dei certificati (CRL) per i plug-in di SnapCenter

.A proposito di questa attività
* Per scaricare il file CRL più recente per il certificato CA correlato, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["Come aggiornare il file dell'elenco di revoca dei certificati nel certificato CA di SnapCenter"].
* I plug-in SnapCenter cercheranno i file CRL in una directory preconfigurata.
* La directory predefinita per i file CRL per i plug-in SnapCenter è _'C:\Programmi\NetApp\SnapCenter\Snapcenter Plug-in Creator\ etc\crl'_.


.Fasi
. È possibile modificare e aggiornare la directory predefinita nel file _agent.properties_ in base alla chiave CRL_PATH.
. È possibile inserire più file CRL in questa directory.
+
I certificati in entrata verranno verificati per ciascun CRL.


