---
permalink: protect-mysql/how-snapcenter-plug-in-for-mysql-uses-consistency-group-snapshot-copies.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: 'È possibile utilizzare il plug-in per creare snapshot del gruppo di coerenza per i gruppi di risorse. Un gruppo di coerenza è un container che può ospitare più volumi in modo da poterli gestire come un"unica entità. Un gruppo di coerenza è costituito da snapshot simultanee di più volumi, che offrono copie coerenti di un gruppo di volumi.' 
---
= In che modo il plug-in SnapCenter per MySQL utilizza le snapshot di gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il plug-in per creare snapshot del gruppo di coerenza per i gruppi di risorse. Un gruppo di coerenza è un container che può ospitare più volumi in modo da poterli gestire come un'unica entità. Un gruppo di coerenza è costituito da snapshot simultanee di più volumi, che offrono copie coerenti di un gruppo di volumi.

Puoi anche specificare il tempo di attesa per lo storage controller che raggruppa le snapshot in modo coerente. Le opzioni di tempo di attesa disponibili sono *urgente*, *Medio* e *rilassato*. È inoltre possibile attivare o disattivare la sincronizzazione WAFL (Write Anywhere file Layout) durante l'operazione di snapshot di gruppo coerente. WAFL Sync migliora le prestazioni di una snapshot del gruppo di coerenza.
